#!/usr/bin/env python3
"""Emit English-only red-team artifacts for redbase-odd. KEEP is proposal only."""
from __future__ import annotations

import hashlib
import json
from collections import Counter
from pathlib import Path

OUT = Path("/home/hanqing/agents/ai-slop/autoresearch/herdr-260813-ghsa200-redbase-odd")
CACHE = Path("/home/hanqing/.cache/ghsa200-worker-clones/redbase-odd")
LEDGER = Path(
    "/home/hanqing/agents/ai-slop/autoresearch/orchestrator-260813-fp211-canonical/ledger.jsonl"
)
ASSIGNED = [
    19, 23, 27, 39, 43, 49, 57, 63, 65, 73, 81, 111, 119, 135, 137, 147, 161, 163, 167, 171, 179, 185,
]
NOTE = (
    "Red-team KEEP is a proposal, not leader admission. "
    "Prior ledger labels were hypotheses only."
)


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def gsha(name: str) -> str | None:
    path = CACHE / "pages" / name
    if not path.is_file() or path.stat().st_size < 200:
        return None
    raw = path.read_bytes()
    if raw.startswith(b'{"message":"Not Found"'):
        return None
    return hashlib.sha256(raw).hexdigest()


HEADS = {
    "ebay-mcp": ("fe295c3da1d65b717a6ff7ea750ce20955172e62", "2026-08-07T18:18:10+03:00"),
    "openclaw": ("2dcd47d4f45f0bdd1e22c707ac26e33991b7a37a", "2026-08-13T13:49:00-07:00"),
    "zeptoclaw": ("6c74d59fc2853cd81df191fb1da02fa514573c8a", "2026-07-25T01:49:50+08:00"),
    "coolify": ("a02d02d19bedd3b68880721d449a646559e234ea", "2026-08-13T21:38:23+02:00"),
    "agentic-flow": ("d3735a33533da2e12a68439177a791bf1c5c91e1", "2026-07-29T21:18:20-04:00"),
    "zae-limiter": ("ced59de08fc227d9de9826671d83f4b79b52180f", "2026-06-25T23:00:42-04:00"),
    "mail-mcp-bridge": ("638b162b26532e32fa8d8047f638537dbdfe197a", "2026-04-12T20:51:11+08:00"),
    "clawdbot-feishu": ("b07885b756accb6756ddf696b60972a413317287", "2026-03-29T23:07:33+08:00"),
    "misp": ("4af1c16d3f23cf90239b68050dd530e749e7edfd", "2026-08-13T10:39:02+02:00"),
    "bsv-ruby-sdk": ("791b49b724af9809d63ed24ebba91252311d3d43", "2026-07-08T10:46:53+01:00"),
    "fireshare": ("7889e7f1166c5092c42a00768d03a3182d23193b", "2026-08-08T08:33:21-06:00"),
    "vm2": ("7a1f5100b96f48d34e0fe104ab37c0acc5944f92", "2026-05-19T00:24:37+09:00"),
    "n8n-mcp": ("5e3c425faaf0823b320c67ed8936903b00c55267", "2026-08-09T12:48:38+02:00"),
    "locutus": ("0f8ed0e29dd1d8073a718d4c2226a330eb9c4e46", "2026-05-16T12:15:55+02:00"),
    "scriban": ("420513a9d017fa54b23ba78a9f21a12187a8dd97", "2026-07-29T09:18:31+02:00"),
    "GitPython": ("f44c1fb0e5dc3b3f0df58c7834ceed336f0d36fc", "2026-08-11T15:54:56+02:00"),
    "churchcrm": ("d8d0f16369d6c15bc7c1860ba114ea82c014de6c", "2026-08-12T08:48:31-07:00"),
}


def C(**kw):
    row = {
        "schema_version": 1,
        "row_kind": "red_team_gate_review",
        "lane": "redbase-odd",
        "language": "en",
        "note": NOTE,
        "worker_hypothesis_verdict": "CONFIRM",
    }
    row.update(kw)
    return row


def build_cases() -> list[dict]:
    return [
        C(
            ordinal=19,
            case_id="GHSA-97RM-XJ73-33JH",
            aliases=["CVE-2026-27203"],
            repository="YosefHayim/ebay-mcp",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="ebay-mcp.env-token-writeback.unescaped-newline-injection",
            candidate_set=["4c9c826c6fc8b64a20e948cb46fefdda42d5244d"],
            carrier_set=[],
            minimum_fix_set=["aab0bda75ea9dd27aa37d0d8524d7cf41b3c4a9a"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count Claude commit 4c9c826c, which first added updateEnvFile raw key=value writeback of tokens into .env.",
            ai_marker_evidence="Author and committer of 4c9c826c are Claude <noreply@anthropic.com>. Parent has no updateEnvFile. v1.7.2 contains the helper; aab0bda7 is absent from v1.7.2 and present in v1.7.3.",
            first_party_sources=[
                "https://github.com/YosefHayim/ebay-mcp/security/advisories/GHSA-97rm-xj73-33jh",
                "https://github.com/advisories/GHSA-97rm-xj73-33jh",
            ],
            source_hashes={
                "global_ghsa_sha256": gsha("GHSA-97RM-XJ73-33JH.json"),
                "repo_ghsa_sha256": gsha("repo-YosefHayim_ebay-mcp-GHSA-97RM-XJ73-33JH.json"),
                "repo_head": HEADS["ebay-mcp"][0],
            },
            vulnerable_release={"kind": "git_tag", "tag": "v1.7.2", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v1.7.3", "contains_fix_ancestor": True},
            counterevidence=["No Co-Authored-By trailer; Claude noreply authorship is the marker.", "Repo advisory names ebay_set_user_tokens / updateEnvFile newline injection."],
            baseline_overlap="fp211 ordinal 19 CONFIRM/HIGH released-admitted. Independent replay agrees.",
        ),
        C(
            ordinal=23,
            case_id="GHSA-VVGP-4C28-M3JM",
            aliases=["CVE-2026-32057"],
            repository="openclaw/openclaw",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="trusted_proxy_control_ui_node_pairing_bypass",
            candidate_set=["20523b918adff4feae378ac9965e204c56b6e3d8"],
            carrier_set=[],
            supporting_member=["4a7b813a4f70946aa2b9401a3fd6865f32c5f9b9"],
            minimum_fix_set=["ec45c317f5d0631a3d333b236da58c4749ede2a3"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count released squash 20523b91, which first added trustedProxyAuthOk pairing bypass without role===operator. Member 4a7b813a is supporting provenance only.",
            ai_marker_evidence="20523b91 and fetched member 4a7b813a contain Co-authored-by: Cursor <cursoragent@cursor.com>. Squash parent has no trustedProxyAuthOk. Member/squash/v2026.2.24 blobs for connect-policy.ts and message-handler.ts are identical. Blame of trustedProxyAuthOk on v2026.2.24 is 20523b91. Fix ec45c317 adds role === \"operator\".",
            first_party_sources=["https://github.com/openclaw/openclaw/security/advisories/GHSA-vvgp-4c28-m3jm"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-VVGP-4C28-M3JM.json"), "repo_ghsa_sha256": gsha("repo-openclaw_openclaw-GHSA-VVGP-4C28-M3JM.json"), "repo_head": HEADS["openclaw"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v2026.2.24", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v2026.2.25", "contains_fix_ancestor": True},
            counterevidence=["Member 4a7b813a is not an ancestor of v2026.2.24.", "Distinct from ordinal 81 GHSA-RV39 hasTokenAuth skip."],
            baseline_overlap="fp211 listed the PR member as candidate and the squash as carrier. Independent replay binds the shipped hunk to the Cursor-marked squash.",
        ),
        C(
            ordinal=27,
            case_id="GHSA-46Q5-G3J9-WX5C",
            aliases=["CVE-2026-32231"],
            repository="qhkm/zeptoclaw",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="zeptoclaw.webhook.client-supplied-sender-chat-id",
            candidate_set=["2c9deefbf744089c3041885717b92c6f2fc0bf8c"],
            carrier_set=[],
            minimum_fix_set=["bf004a20d3687a0c1a9e052ec79536e30d6de134"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count squash 2c9deefb first adding src/channels/webhook.rs with caller-supplied sender/chat_id and default auth_token None.",
            ai_marker_evidence="2c9deefb contains Co-Authored-By: Claude Opus 4.6. Parent has no webhook.rs. Candidate in v0.7.5; fix bf004a20 first in v0.7.6.",
            first_party_sources=["https://github.com/qhkm/zeptoclaw/security/advisories/GHSA-46q5-g3j9-wx5c"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-46Q5-G3J9-WX5C.json"), "repo_ghsa_sha256": gsha("repo-qhkm_zeptoclaw-GHSA-46Q5-G3J9-WX5C.json"), "repo_head": HEADS["zeptoclaw"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v0.7.5", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v0.7.6", "contains_fix_ancestor": True},
            counterevidence=["Same squash adds unrelated features. Same fix also hardens WhatsApp and filesystem; this row's origin is webhook identity only."],
            baseline_overlap="fp211 CONFIRM. Independent replay confirms parent absence of webhook.rs.",
        ),
        C(
            ordinal=39,
            case_id="GHSA-X9QH-W4C4-54F9",
            aliases=["CVE-2026-42148"],
            repository="coollabsio/coolify",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="coolify.buildHelperImage.dev_helper_version.unescaped_docker_build_shell",
            candidate_set=["18f30b7fabc54938a031867ad34c39a1e9c7c0d7"],
            carrier_set=[],
            minimum_fix_set=["dc9322b11f5f4ab96e56af0df7d4f877e96e5e4c"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count 18f30b7f first adding buildHelperImage interpolating {$version} into docker build. Official range <=beta.473 has no lower bound; git introduction is this commit / v4.0.0-beta.447.",
            ai_marker_evidence="18f30b7f has Co-Authored-By: Claude. Parent Index.php has no buildHelperImage. Blame on v4.0.0-beta.447 is 18f30b7f. Fix dc9322b1 is first in v4.0.0-beta.474.",
            first_party_sources=["https://github.com/coollabsio/coolify/security/advisories/GHSA-x9qh-w4c4-54f9"],
            source_hashes={"global_ghsa_sha256": None, "repo_ghsa_sha256": gsha("repo-coollabsio_coolify-GHSA-X9QH-W4C4-54F9.json"), "repo_head": HEADS["coolify"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v4.0.0-beta.447", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v4.0.0-beta.474", "contains_fix_ancestor": True},
            counterevidence=["Commit subject is unrelated; the docker-build hunk is in that commit.", "Global GHSA API 404; repo advisory aliases CVE-2026-42148."],
            baseline_overlap="fp211 already treated repo GHSA as identity when the global object 404s. Independent fetch agrees.",
        ),
        C(
            ordinal=43,
            case_id="GHSA-VCV2-R9JH-99M5",
            aliases=["CVE-2026-58195"],
            repository="ruvnet/agentic-flow",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="agentic-flow.mcp.execSync.unsanitized_tool_parameter_shell_interpolation",
            candidate_set=["2a1e2777dd6a993f678d9596dd7c6c4fd0c444d9", "319c98616bc968b6810c6c0b49e04806e7379530"],
            carrier_set=["68e60a86c92db19c62fe175295a21b073033b31f"],
            minimum_fix_set=["a0f9c2bf95b6203b3e1b24f92a7e390d6774de13"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count Claude-authored execSync(cmd) MCP tool interpolation, including http-sse.ts from 2a1e2777 and restored sibling servers from 319c9861, as shipped in npm 2.0.13.",
            ai_marker_evidence="2a1e2777 and 319c9861 have Claude trailers. Parent of 2a1e2777 lacks http-sse.ts. npm 2.0.13 gitHead aa33d2f07a16 contains both origins and not a0f9c2bf. npm 2.0.14 gitHead is a0f9c2bf (execFileSync).",
            first_party_sources=["https://github.com/ruvnet/agentic-flow/security/advisories/GHSA-vcv2-r9jh-99m5"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-VCV2-R9JH-99M5.json"), "repo_ghsa_sha256": gsha("repo-ruvnet_agentic-flow-GHSA-VCV2-R9JH-99M5.json"), "repo_head": HEADS["agentic-flow"][0]},
            vulnerable_release={"kind": "npm_githead", "version": "2.0.13", "sha": "aa33d2f07a16da6b9cdfc7c9dede4ffde86c1208", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "npm_githead", "version": "2.0.14", "sha": "a0f9c2bf95b6203b3e1b24f92a7e390d6774de13", "contains_fix_ancestor": True},
            counterevidence=["No v2.0.13/v2.0.14 git tags. 2.0.13 gitHead is not an ancestor of 2.0.14 gitHead; containment uses npm gitHead.", "2a1e2777 is not an ancestor of 319c9861."],
            baseline_overlap="fp211 npm_githead story independently reproduced from registry.npmjs.org.",
        ),
        C(
            ordinal=49,
            case_id="GHSA-76RV-2R9V-C5M6",
            aliases=["CVE-2026-27695"],
            repository="zeroae/zae-limiter",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="zae-entity-scoped-dynamodb-hot-partition",
            candidate_set=["3902c8c22868832db6d9f54046e76d5be226f607"],
            carrier_set=[],
            minimum_fix_set=["94a129ae55acc3b034662045296e288279cbef2e"],
            hypothesized_minimum_fix=["9f66c42f06f3b87107ce327bede6416a582f0e60"],
            named_advisory_commit=["481ce44d818d66e31d8837bc48519660ce4c267f"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="NARROW",
            release_gate="PASS",
            uniqueness_gate="NARROW",
            verdict="NARROW",
            worker_disposition="REDTEAM_NARROW",
            note="NARROW preserves the initial-commit origin. It is not a causal PASS. " + NOTE,
            scope_statement="Claude initial commit 3902c8c2 created entity-scoped DynamoDB partition keys. Hypothesized minimum_fix_set 9f66c42f is later shard-selection, not the PK migration.",
            ai_marker_evidence="3902c8c2 is the initial commit with Co-Authored-By: Claude Opus 4.5 and is an ancestor of v0.10.0. v0.10.1 is 481ce44d.",
            first_party_sources=["https://github.com/zeroae/zae-limiter/security/advisories/GHSA-76rv-2r9v-c5m6"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-76RV-2R9V-C5M6.json"), "repo_ghsa_sha256": gsha("repo-zeroae_zae-limiter-GHSA-76RV-2R9V-C5M6.json"), "repo_head": HEADS["zae-limiter"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v0.10.0", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v0.10.1", "sha": "481ce44d818d66e31d8837bc48519660ce4c267f", "contains_fix_ancestor": True},
            counterevidence=["GHSA names 481ce44d, a long pre-shard series.", "94a129ae migrates bucket items to per-shard keys before 9f66c42f.", "9f66c42f is Claude-authored feat(limiter) shard selection, not the first PK reversal."],
            baseline_overlap="fp211 minimum_fix_set 9f66c42f disagrees with release_evidence.fix_sha 481ce44d. Independent history prefers 94a129ae then 481ce44d.",
        ),
        C(
            ordinal=57,
            case_id="GHSA-2GFJ-FR43-4735",
            aliases=["CVE-2026-7386"],
            repository="fatbobman/mail-mcp-bridge",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="mail-mcp-bridge.message_id.strip-concat.path-traversal.extract-and-rmtree",
            candidate_set=["26be5ccbf17501852e98f7699d77ec4f63128ece"],
            carrier_set=[],
            minimum_fix_set=["638b162b26532e32fa8d8047f638537dbdfe197a"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count 26be5ccb, which first added extract/cleanup attachment tools joining message_id.strip('<>') as a directory then shutil.rmtree.",
            ai_marker_evidence="26be5ccb body contains Generated with Claude Code. Parent lacks the attachment modules. Candidate in v1.1.0; fix 638b162b first in tag 1.3.4.",
            first_party_sources=["https://github.com/advisories/GHSA-2gfj-fr43-4735", "https://github.com/fatbobman/mail-mcp-bridge/commit/638b162b26532e32fa8d8047f638537dbdfe197a"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-2GFJ-FR43-4735.json"), "repo_ghsa_sha256": None, "repo_head": HEADS["mail-mcp-bridge"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v1.1.0", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "1.3.4", "contains_fix_ancestor": True},
            counterevidence=["No repo security advisory (404). Identity is the GitHub global GHSA derived from CVE-2026-7386 plus the named fix commit.", "No git tag 1.3.3 even though NVD says up to 1.3.3."],
            baseline_overlap="fp211 CONFIRM. Independent replay confirms Claude Code marker, strip+rmtree, and 1.3.4 containment.",
        ),
        C(
            ordinal=63,
            case_id="GHSA-4564-PVR2-QQ4H",
            aliases=["CVE-2026-27487"],
            repository="openclaw/openclaw",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="openclaw.macos-claude-cli.oauth-refresh.execSync-security",
            candidate_set=["a39951d463b9c5377cbe7e08d6953899dca708d8"],
            carrier_set=[],
            minimum_fix_set=["9dce3d8bf83f13c067bc3c32291643d2f1f10a06"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count a39951d4 OAuth refresh path that interpolates token JSON into execSync security add-generic-password -w. Minimum reversal is 9dce3d8b execFileSync on the write.",
            ai_marker_evidence="a39951d4 has Co-Authored-By Claude. Candidate in v2026.2.13; 9dce3d8b not in that tag and is in v2026.2.14.",
            first_party_sources=["https://github.com/openclaw/openclaw/security/advisories/GHSA-4564-pvr2-qq4h"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-4564-PVR2-QQ4H.json"), "repo_ghsa_sha256": gsha("repo-openclaw_openclaw-GHSA-4564-PVR2-QQ4H.json"), "repo_head": HEADS["openclaw"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v2026.2.13", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v2026.2.14", "contains_fix_ancestor": True},
            counterevidence=["GHSA also lists 66d7178f (human follow-up eliminating remaining execSync on find-generic-password) and b9083882 (test cleanup). 9dce3d8b already switches the named -w write to execFileSync.", "Fix author Aether AI is later remediator, not origin."],
            baseline_overlap="fp211 minimum_fix_set 9dce3d8b matches the write-path reversal. Independent replay keeps that minimum and treats 66d7178f as extra hardening.",
        ),
        C(
            ordinal=65,
            case_id="GHSA-C6HR-W26Q-C636",
            aliases=["CVE-2026-22178"],
            repository="openclaw/openclaw",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="openclaw.feishu.stripBotMention.unescaped-regexp-from-mention-metadata",
            candidate_set=["4286755f26bcfdd5c704cc4eb0cabfdc1b314e68"],
            carrier_set=["2267d58afcc70fe19408b8f0dce108c340f3426d"],
            minimum_fix_set=["7e67ab75cc2f0e93569d12fecd1411c2961fcc8c"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count upstream Claude root 4286755f new RegExp(`@${mention.name}`) / new RegExp(mention.key) in stripBotMention, imported by openclaw 2267d58a, reversed by 7e67ab75 escapeRegExp.",
            ai_marker_evidence="Upstream m1heng/clawdbot-feishu 4286755f is Initial release v0.1.0 with Co-Authored-By: Claude Opus 4.5 and contains the unescaped RegExp. Openclaw carrier 2267d58a copies stripBotMention; it is in v2026.2.6 and v2026.2.17. Fix 7e67ab75 is not in v2026.2.17 and is in v2026.2.19.",
            first_party_sources=["https://github.com/openclaw/openclaw/security/advisories/GHSA-c6hr-w26q-c636"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-C6HR-W26Q-C636.json"), "repo_ghsa_sha256": gsha("repo-openclaw_openclaw-GHSA-C6HR-W26Q-C636.json"), "repo_head": HEADS["openclaw"][0], "upstream_head": HEADS["clawdbot-feishu"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v2026.2.17", "contains_carrier_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v2026.2.19", "contains_fix_ancestor": True},
            counterevidence=["4286755f is not an object in openclaw; topology is upstream atomic plus import carrier.", "Repo advisory identifiers omit CVE; global GHSA lists CVE-2026-22178 for the same GHSA id.", "Named extra commit 74268489 is tests/CHANGELOG only.", "Shared upstream SHA does not merge this regex-injection sink with other Feishu mechanisms."],
            baseline_overlap="fp211 missing top-level mechanism_key. Independent fingerprint is stripBotMention unescaped RegExp from mention metadata.",
        ),
        C(
            ordinal=73,
            case_id="GHSA-243V-5F97-VFQ3",
            aliases=["CVE-2026-10855"],
            repository="MISP/MISP",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="misp.EventTemplateImporter.overwrite.missing-org-ownership",
            candidate_set=["41450bdb5d31ab017e147ccc921951ee6a70e134"],
            carrier_set=[],
            minimum_fix_set=["7c2200d143bef86aaf58d701b6968a843097db69"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count 41450bdb adding EventTemplateImporter overwrite that preserves org_id without checking the caller's org.",
            ai_marker_evidence="41450bdb contains Co-Authored-By: Claude Opus 4.7. Candidate in v2.5.37; fix 7c2200d1 (3-line org check) first in v2.5.39.",
            first_party_sources=["https://github.com/advisories/GHSA-243v-5f97-vfq3", "https://github.com/MISP/MISP/commit/7c2200d143bef86aaf58d701b6968a843097db69"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-243V-5F97-VFQ3.json"), "repo_ghsa_sha256": None, "repo_head": HEADS["misp"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v2.5.37", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v2.5.39", "contains_fix_ancestor": True},
            counterevidence=["No repo security advisory. Global GHSA is NVD-imported (github_reviewed null) but names the first-party fix commit.", "v2.5.38 was not used as the last-vulnerable tag; v2.5.37 contains origin without the org check."],
            baseline_overlap="fp211 CONFIRM. Independent replay confirms Claude trailer and the three-line ownership check.",
        ),
        C(
            ordinal=81,
            case_id="GHSA-RV39-79C4-7459",
            aliases=["CVE-2026-28472"],
            repository="openclaw/openclaw",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="openclaw.gateway.hasTokenAuth.unvalidated-token-presence-device-bypass",
            candidate_set=["079af0d0b02ca2c722f90b6c4e38e27ba16227b4"],
            carrier_set=[],
            minimum_fix_set=["fe81b1d7125a014b8280da461f34efbf5f761575"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count 079af0d0, which first skipped device identity when connectParams.auth.token was merely present. Distinct from ordinal 23 trusted-proxy pairing.",
            ai_marker_evidence="079af0d0 subject is 'allow token auth to bypass device identity' with Co-Authored-By: Claude Opus 4.5. Parent message-handler lacks hasTokenAuth. Candidate in v2026.2.1; fe81b1d7 requires sharedAuthOk and is first in v2026.2.2.",
            first_party_sources=["https://github.com/openclaw/openclaw/security/advisories/GHSA-rv39-79c4-7459"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-RV39-79C4-7459.json"), "repo_ghsa_sha256": gsha("repo-openclaw_openclaw-GHSA-RV39-79C4-7459.json"), "repo_head": HEADS["openclaw"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v2026.2.1", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v2026.2.2", "contains_fix_ancestor": True},
            counterevidence=["Remediation-as-origin: the AI commit intentionally added the insecure predicate as a Control UI fix.", "Shared SHA with other gateway rows does not merge token-presence vs trusted-proxy invariants."],
            baseline_overlap="fp211 missing mechanism_key. Independent fingerprint is unvalidated token-presence skip of device identity.",
        ),
        C(
            ordinal=111,
            case_id="GHSA-9HFR-GW99-8RHX",
            aliases=["CVE-2026-40069"],
            repository="sgbett/bsv-ruby-sdk",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="bsv-sdk.arc.txStatus-invalid-malformed-orphan-treated-success",
            candidate_set=["a1f2e62cb3dc48014c1770ec44d61811ae4b7105"],
            carrier_set=["61cca91368693927436cda964fef231068ac3744"],
            minimum_fix_set=["db97de475518eef752ed52b25f49f09cbe24c187"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="NARROW",
            release_gate="PASS",
            uniqueness_gate="NARROW",
            verdict="NARROW",
            worker_disposition="REDTEAM_NARROW",
            note="NARROW preserves the ARC failure-as-success origin. It is not a causal PASS. " + NOTE,
            scope_statement="Claude a1f2e62c added ARC REJECTED_STATUSES = REJECTED, DOUBLE_SPEND_ATTEMPTED only, treating INVALID/MALFORMED/ORPHAN as success. The named security commit also patches var_int and wallet P0s.",
            ai_marker_evidence="a1f2e62c has Co-Authored-By: Claude Opus 4.6. Candidate and merge carrier 61cca913 are ancestors of v0.8.1. db97de47 is not in v0.8.1 and is in v0.8.2 via squash 4992e8a2.",
            first_party_sources=["https://github.com/sgbett/bsv-ruby-sdk/security/advisories/GHSA-9hfr-gw99-8rhx"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-9HFR-GW99-8RHX.json"), "repo_ghsa_sha256": gsha("repo-sgbett_bsv-ruby-sdk-GHSA-9HFR-GW99-8RHX.json"), "repo_head": HEADS["bsv-ruby-sdk"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v0.8.1", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v0.8.2", "contains_fix_ancestor": True},
            counterevidence=["db97de47 message: three P0 findings (ARC + var_int + wallet). Umbrella fix.", "Fix commit is also Claude-marked; that is remediator identity, not a second origin."],
            baseline_overlap="fp211 CONFIRM with member db97de47 vs named 4992e8a2. Independent replay confirms member-in-squash and umbrella packaging.",
        ),
        C(
            ordinal=119,
            case_id="GHSA-9F72-QCPW-2HXC",
            aliases=[],
            repository="openclaw/openclaw",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="openclaw.prompt-image-autoload.missing-workspaceOnly",
            candidate_set=["8d74578ceb0c3b913555dff6265821eb0fc09749"],
            carrier_set=[],
            minimum_fix_set=["370d115549c0dadace0902775eea0d5094aedfdc"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count 8d74578c detectAndLoadPromptImages, which loads prompt image paths without tools.fs.workspaceOnly. Sharing this SHA with other image/decoder rows is not a duplicate.",
            ai_marker_evidence="8d74578c has Co-Authored-By: Claude Opus 4.5 and adds detectAndLoadPromptImages. Candidate in v2026.1.20 and v2026.2.23; 370d1155 is not in v2026.2.23 and is in v2026.2.24.",
            first_party_sources=["https://github.com/openclaw/openclaw/security/advisories/GHSA-9f72-qcpw-2hxc"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-9F72-QCPW-2HXC.json"), "repo_ghsa_sha256": gsha("repo-openclaw_openclaw-GHSA-9F72-QCPW-2HXC.json"), "repo_head": HEADS["openclaw"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v2026.2.23", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v2026.2.24", "contains_fix_ancestor": True},
            counterevidence=["Candidate text mentions sandbox path validation; it still omits workspaceOnly, which is the GHSA invariant.", "GHSA-only (no CVE)."],
            baseline_overlap="fp211 missing mechanism_key. Independent fingerprint is native prompt-image autoload vs workspaceOnly.",
        ),
        C(
            ordinal=135,
            case_id="GHSA-FVVP-RJ8G-C7GC",
            aliases=["CVE-2026-34745"],
            repository="ShaneIsrael/fireshare",
            contribution_class="AI_INCOMPLETE_REMEDIATION",
            mechanism_key="fireshare.public-uploadChunked.checkSum-unsanitized-temp-path",
            candidate_set=["157386c85f6683f89192dae52115069b435b6d34"],
            carrier_set=["b76915607924756e6fa1a5f6c8823c38d611fb24"],
            minimum_fix_set=["70b5b35aadd55c7936a25effd6f3e9ee4c124879"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count Copilot 157386c8, which applied secure_filename to upload names including /api/uploadChunked/public while leaving form checkSum concatenated into the temp path. Residual closed by 70b5b35a / merge b7691560 in v1.5.3.",
            ai_marker_evidence="157386c8 author is copilot-swe-agent[bot]. Parent already had checkSum in tempPath; this commit is the incomplete filename rem named by the repo advisory as the CVE-2026-33645 leftover on the public endpoint. Candidate in v1.3.0 and v1.5.2; 70b5b35a not in v1.5.2 and in v1.5.3.",
            first_party_sources=["https://github.com/ShaneIsrael/fireshare/security/advisories/GHSA-fvvp-rj8g-c7gc"],
            source_hashes={"global_ghsa_sha256": None, "repo_ghsa_sha256": gsha("repo-ShaneIsrael_fireshare-GHSA-FVVP-RJ8G-C7GC.json"), "repo_head": HEADS["fireshare"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v1.5.2", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v1.5.3", "contains_fix_ancestor": True},
            counterevidence=["Global GHSA API 404; repo advisory is first-party and aliases CVE-2026-34745.", "Old-bug preservation of the checksum path is real; this row is incomplete rem of the adjacent filename fix, which the advisory states explicitly.", "Official range <=1.5.2 has no lower bound."],
            baseline_overlap="fp211 AI_INCOMPLETE_REMEDIATION. Independent repo advisory text matches the copilot filename-only patch leftover.",
        ),
        C(
            ordinal=137,
            case_id="GHSA-M4WX-M65X-GHRR",
            aliases=["CVE-2026-47137"],
            repository="patriksimek/vm2",
            contribution_class="AI_INCOMPLETE_REMEDIATION",
            mechanism_key="vm2.nodevm.nesting-true.require-undefined.strict-equality-bypass",
            candidate_set=["46cbbdde4e19b743974c942278080231004146ca"],
            carrier_set=[],
            minimum_fix_set=["86ab819f202c3a8dad88cef5705f2e416c5188d7"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count peeled v3.11.1 Claude patch 46cbbdde, which rejects only {nesting:true, require:false} via === false and documents omit-require as out of scope. Complete guard 86ab819f first in v3.11.4.",
            ai_marker_evidence="46cbbdde equals v3.11.1^{commit}, has Claude trailer, and contains options.nesting === true && options.require === false. Human 01a7552 is not an ancestor of v3.11.1-v3.11.3. 86ab819f is not in v3.11.3 and is in v3.11.4.",
            first_party_sources=["https://github.com/patriksimek/vm2/security/advisories/GHSA-m4wx-m65x-ghrr"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-M4WX-M65X-GHRR.json"), "repo_ghsa_sha256": gsha("repo-patriksimek_vm2-GHSA-M4WX-M65X-GHRR.json"), "repo_head": HEADS["vm2"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v3.11.3", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v3.11.4", "contains_fix_ancestor": True},
            counterevidence=["Do not use git tag --contains on shallow clones; merge-base --is-ancestor is the ancestry oracle.", "Pre-3.11.1 nesting RCE is the 2023 bug; this GHSA is the incomplete 3.11.1 constructor check."],
            baseline_overlap="fp211 CONFIRM incomplete rem. Independent merge-base agrees 01a7552 is absent from v3.11.1-3.11.3.",
        ),
        C(
            ordinal=147,
            case_id="GHSA-56C3-VFP2-5QQJ",
            aliases=["CVE-2026-42449"],
            repository="czlonkowski/n8n-mcp",
            contribution_class="AI_INCOMPLETE_REMEDIATION",
            mechanism_key="n8n-mcp.validateUrlSync.ipv4-only.ipv4-mapped-ipv6-ssrf",
            candidate_set=["d9d847f230923d96e0857ccecf3a4dedcc9b0096"],
            carrier_set=[],
            minimum_fix_set=["9639f757853149f0cb16663cc8b6b6468f27a25f"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count Claude-coauthored fork-merge d9d847f2 adding IPv4-only validateUrlSync, first in v2.47.4. Residual IPv4-mapped IPv6 closed by 9639f757 in v2.47.14.",
            ai_marker_evidence="d9d847f2 is a merge commit with Co-authored-by: Claude Opus 4.6. Parent 643c98bc lacks validateUrlSync. Candidate in v2.47.4 through v2.47.13; fix first in v2.47.14.",
            first_party_sources=["https://github.com/czlonkowski/n8n-mcp/security/advisories/GHSA-56c3-vfp2-5qqj"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-56C3-VFP2-5QQJ.json"), "repo_ghsa_sha256": gsha("repo-czlonkowski_n8n-mcp-GHSA-56C3-VFP2-5QQJ.json"), "repo_head": HEADS["n8n-mcp"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v2.47.13", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v2.47.14", "contains_fix_ancestor": True},
            counterevidence=["Official range starts at 2.47.4, matching the incomplete rem introduction, unlike scriban 163/167."],
            baseline_overlap="fp211 incomplete rem. Independent tag ancestry matches v2.47.4-v2.47.13 vs v2.47.14.",
        ),
        C(
            ordinal=161,
            case_id="GHSA-VC8F-X9PP-WF5P",
            aliases=["CVE-2026-33994"],
            repository="locutusjs/locutus",
            contribution_class="AI_INCOMPLETE_REMEDIATION",
            mechanism_key="locutus.parse_str.regexp-test-prototype-guard-overwrite",
            candidate_set=["042af9ca7fde2ff599120783e720a17f335bb01c"],
            carrier_set=[],
            minimum_fix_set=["345a6211e1e6f939f96a7090bfeff642c9fcf9e4"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count Claude 042af9ca replacing key.includes(...) with /__proto__|constructor|prototype/.test(key) in parse_str. Residual is overwriting RegExp.prototype.test, closed in v3.0.25.",
            ai_marker_evidence="042af9ca has Co-Authored-By: Claude Opus 4.5 and is first in v2.0.39. Official range >=2.0.39 <3.0.25. 345a6211 first in v3.0.25.",
            first_party_sources=["https://github.com/locutusjs/locutus/security/advisories/GHSA-vc8f-x9pp-wf5p"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-VC8F-X9PP-WF5P.json"), "repo_ghsa_sha256": gsha("repo-locutusjs_locutus-GHSA-VC8F-X9PP-WF5P.json"), "repo_head": HEADS["locutus"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "v2.0.39", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "v3.0.25", "contains_fix_ancestor": True},
            counterevidence=["This is incomplete rem of CVE-2026-25521 / GHSA-rxrv, not a new parse_str sink from whole-cloth."],
            baseline_overlap="fp211 incomplete rem. Independent diff is includes() to RegExp.test().",
        ),
        C(
            ordinal=163,
            case_id="GHSA-Q6RR-FM2G-G5X8",
            aliases=[],
            repository="scriban/scriban",
            contribution_class="AI_INCOMPLETE_REMEDIATION",
            mechanism_key="scriban.scriptarray.tryevaluate.array-int-multiply.unbounded-allocation",
            candidate_set=["2d01bd15a1114fac2533aa005036e07389ee89db"],
            carrier_set=[],
            minimum_fix_set=["205ca6a7c2349d3d388bd5f1f7729ee198c0d5e5"],
            identity_gate="NARROW",
            ai_hunk_gate="NARROW",
            topology_gate="PASS",
            but_for_gate="NARROW",
            fix_reversal_gate="PASS",
            release_gate="NARROW",
            uniqueness_gate="PASS",
            verdict="NARROW",
            worker_disposition="REDTEAM_NARROW",
            note="NARROW preserves Copilot LoopLimit on sibling operators. It is not a GHSA-level KEEP. " + NOTE,
            scope_statement="Copilot 2d01bd15 (first in 7.0.0) hardens ScriptBinaryExpression LoopLimit and does not touch ScriptArray.cs. Official GHSA range is >=3.0.0, before the candidate. Array*int unbounded allocation is an old sibling, not an AI-authored sink.",
            ai_marker_evidence="2d01bd15 has Co-authored-by: Copilot and is an ancestor of 7.0.0-7.2.0. 205ca6a7 edits ScriptArray.cs and is first in 7.2.1.",
            first_party_sources=["https://github.com/scriban/scriban/security/advisories/GHSA-q6rr-fm2g-g5x8"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-Q6RR-FM2G-G5X8.json"), "repo_ghsa_sha256": gsha("repo-scriban_scriban-GHSA-Q6RR-FM2G-G5X8.json"), "repo_head": HEADS["scriban"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "7.2.0", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "7.2.1", "contains_fix_ancestor": True},
            counterevidence=["Official affected range starts at 3.0.0, years before Copilot 7.0.0.", "Candidate files: ScriptBinaryExpression.cs / ArrayFunctions.cs, not ScriptArray.TryEvaluate.", "Distinct from ordinal 167 parser-depth."],
            baseline_overlap="fp211 CONFIRM incomplete rem. Independent file list and range lower bound refuse GHSA-level DIRECT/incomplete KEEP.",
        ),
        C(
            ordinal=167,
            case_id="GHSA-6Q7J-XR26-3H2C",
            aliases=[],
            repository="scriban/scriban",
            contribution_class="AI_INCOMPLETE_REMEDIATION",
            mechanism_key="scriban.parser.EnterExpression.logerror-continue.non-enforcing-depth-limit",
            candidate_set=["f55280a09575e577fcf7f5629007e0814594e3ac"],
            carrier_set=[],
            minimum_fix_set=["8fdbd687bbe8f00085c4c4c5b2b3b8d529933949"],
            identity_gate="NARROW",
            ai_hunk_gate="NARROW",
            topology_gate="PASS",
            but_for_gate="NARROW",
            fix_reversal_gate="PASS",
            release_gate="NARROW",
            uniqueness_gate="PASS",
            verdict="NARROW",
            worker_disposition="REDTEAM_NARROW",
            note="NARROW preserves Copilot array-initializer depth accounting. It is not a GHSA-level KEEP. " + NOTE,
            scope_statement="Non-enforcing ExpressionDepthLimit (LogError then continue) originates in b5ac4bf / 6.6.0, before Copilot f55280a0 (2026-03-21) which extends EnterExpression to array initializers using the same non-abort pattern. Official range >=6.6.0.",
            ai_marker_evidence="f55280a0 has Co-authored-by: Copilot and is first in 7.0.0, not in 6.6.0. 8fdbd687 first in 7.2.1.",
            first_party_sources=["https://github.com/scriban/scriban/security/advisories/GHSA-6q7j-xr26-3h2c"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-6Q7J-XR26-3H2C.json"), "repo_ghsa_sha256": gsha("repo-scriban_scriban-GHSA-6Q7J-XR26-3H2C.json"), "repo_head": HEADS["scriban"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "7.2.0", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "7.2.1", "contains_fix_ancestor": True},
            counterevidence=["b5ac4bf 'Add limits for default safety' (Dishan Sachin, 2026-03-19) is an ancestor of 6.6.0 and already has EnterExpression.", "Old-bug preservation of the non-enforcing guard.", "Distinct from ordinal 163 array*int."],
            baseline_overlap="fp211 CONFIRM incomplete rem. Independent dates show Copilot two days after the 6.6.0 guard.",
        ),
        C(
            ordinal=171,
            case_id="GHSA-MV93-W799-CJ2W",
            aliases=[],
            repository="gitpython-developers/GitPython",
            contribution_class="AI_INCOMPLETE_REMEDIATION",
            mechanism_key="gitpython.config_writer.section-option-newline.bypasses-value-only-guard",
            candidate_set=["c417af469f9aa3da8dfef78f996c0fb8c5d1f4c2"],
            carrier_set=[],
            minimum_fix_set=["54538428f79b0c91ba52cda5229856a6edf7ac06"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count Codex c417af46 _value_to_string_safe on values only (3.1.49 / CVE-2026-42215). Residual section/option newline injection closed by 54538428 in 3.1.50.",
            ai_marker_evidence="c417af46 author is GPT 5.5 / codex@openai.com. Candidate in 3.1.49; 54538428 not in 3.1.49 and in 3.1.50. Completing fix is also Codex-authored.",
            first_party_sources=["https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-mv93-w799-cj2w"],
            source_hashes={"global_ghsa_sha256": gsha("GHSA-MV93-W799-CJ2W.json"), "repo_ghsa_sha256": gsha("repo-gitpython-developers_GitPython-GHSA-MV93-W799-CJ2W.json"), "repo_head": HEADS["GitPython"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "3.1.49", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "3.1.50", "contains_fix_ancestor": True},
            counterevidence=["Official range <=3.1.49 has no lower bound; the GHSA is framed as bypass of the 3.1.49 value-only patch.", "Distinct from ordinal 179 blame --contents."],
            baseline_overlap="fp211 incomplete rem. Independent show of config.py matches value-only vs section validation.",
        ),
        C(
            ordinal=179,
            case_id="GHSA-5XXX-QHH7-9287",
            aliases=[],
            repository="gitpython-developers/GitPython",
            contribution_class="AI_INCOMPLETE_REMEDIATION",
            mechanism_key="gitpython.repo.blame.unsafe_git_revision_options.omits-contents-S",
            candidate_set=["701ce32fe5ba8cb622c0e0342a376a6beb47d738"],
            carrier_set=[],
            minimum_fix_set=["1b0d2d9b91575f7db44ef4ff58ac37fc9335e5f6"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count Codex 701ce32f denylist unsafe_git_revision_options = --output/-o used by Repo.blame, omitting --contents/-S. Closed by 1b0d2d9b in 3.1.59.",
            ai_marker_evidence="701ce32f author is GPT 5.6 / codex@openai.com, first in 3.1.51 through 3.1.58. 1b0d2d9b (also Codex) first in 3.1.59.",
            first_party_sources=["https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-5xxx-qhh7-9287"],
            source_hashes={"global_ghsa_sha256": None, "repo_ghsa_sha256": gsha("repo-gitpython-developers_GitPython-GHSA-5XXX-QHH7-9287.json"), "repo_head": HEADS["GitPython"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "3.1.58", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "3.1.59", "contains_fix_ancestor": True},
            counterevidence=["Global GHSA API 404; repo advisory 200 is first-party.", "Distinct from config newline (171) and from Diffable.diff sibling advisories."],
            baseline_overlap="fp211 incomplete rem. Independent denylist on 3.1.58 lacks --contents.",
        ),
        C(
            ordinal=185,
            case_id="GHSA-HM7V-JRHM-FMFX",
            aliases=[],
            repository="ChurchCRM/CRM",
            contribution_class="AI_DIRECT_ROOT",
            mechanism_key="churchcrm-shared-person-action-attribute-xss",
            candidate_set=["ede1bfb08633e6d1157744e99d176e258fc58aba"],
            carrier_set=[],
            supporting_member=["6ef78813e04987da217bbb081706715c1ecb19e9"],
            minimum_fix_set=["ae2b73550452056cc45a65a4165340ae17c2c3e5"],
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
            verdict="KEEP",
            worker_disposition="REDTEAM_KEEP_PROPOSAL",
            scope_statement="Count Tabler squash ede1bfb0, which first concatenated person name into quoted data-person_name on the shared renderer. Do not treat later human escapeHtml (54782516) as origin; it is insufficient attribute encoding still present on 7.5.1.",
            ai_marker_evidence="ede1bfb0 has Co-Authored-By: Claude Sonnet 4.6. Parent of squash lacks renderPersonActionMenu data-person_name. Blame of the attribute concatenation on 7.5.1 is ede1bfb0. Member 6ef78813 is not an ancestor of 7.5.1. Fix ae2b7355 switches to escapeAttribute and is first in 7.6.0.",
            first_party_sources=["https://github.com/ChurchCRM/CRM/security/advisories/GHSA-hm7v-jrhm-fmfx"],
            source_hashes={"global_ghsa_sha256": None, "repo_ghsa_sha256": gsha("repo-ChurchCRM_CRM-GHSA-HM7V-JRHM-FMFX.json"), "repo_head": HEADS["churchcrm"][0]},
            vulnerable_release={"kind": "git_tag", "tag": "7.5.1", "contains_candidate_ancestor": True, "contains_fix_ancestor": False},
            fixed_release={"kind": "git_tag", "tag": "7.6.0", "contains_fix_ancestor": True},
            counterevidence=["CRMJSOM.js blobs differ across member/squash/tag.", "Later human 54782516 wraps escapeHtml; 7.5.1 already has escapeAttribute from 33bfcec3 but renderPersonActionMenu still uses escapeHtml.", "ae2b7355 also patches GHSA-m649 and GHSA-6rgg in the same commit (umbrella packaging). Person-action attribute context remains distinct.", "Fetched 5631bb08 is not an ancestor of ae2b7355; released reversal is the merge."],
            baseline_overlap="fp211 used member 6ef78813 plus carrier squash. Independent blame on 7.5.1 binds data-person_name to the Claude squash.",
        ),
    ]


def write_report(cases: list[dict]) -> str:
    lines = [
        "# Red-team: fp211 released-admitted odd ordinals",
        "",
        "**Status: `REDTEAM_COMPLETE`.** Rows with `counting.fp211_released_publication_admitted=true` and `fp211_adjudication.ordinal % 2 == 1` were treated as hypotheses. Independent first-party GHSA fetch and Git replay. A KEEP here is still only a proposal.",
        "",
        f"Assigned ordinals ({len(cases)}): `{ASSIGNED}`.",
        "",
        "| Ordinal | GHSA | Class | Red-team |",
        "|--------:|------|-------|----------|",
    ]
    for c in cases:
        lines.append(
            f"| {c['ordinal']} | {c['case_id']} | {c['contribution_class']} | **{c['verdict']}** |"
        )
    lines += [
        "",
        "Clones: `/home/hanqing/.cache/ghsa200-worker-clones/redbase-odd/clones/`. Advisory JSON: `/home/hanqing/.cache/ghsa200-worker-clones/redbase-odd/pages/`. Sibling even-lane conclusions were not read.",
        "",
        "## Verdicts",
        "",
    ]
    summaries = {
        19: "Claude authored updateEnvFile token writeback. Parent lacks the helper. v1.7.2 / v1.7.3 containment holds. Repo GHSA names the newline injection.",
        23: "Cursor-marked squash 20523b91 adds trustedProxyAuthOk without operator role. Member blobs match the tag but the member is not a tag ancestor. Fix adds role===operator. Distinct from token-presence skip.",
        27: "Claude squash first adds webhook.rs trusting payload.sender/chat_id with auth_token default None. v0.7.5 / v0.7.6. Fix also touches other channels; origin is webhook identity.",
        39: "Repo GHSA (global 404) names unescaped docker build version. Claude commit first adds buildHelperImage. Blame on beta.447 holds. Official range has no lower bound.",
        43: "Two Claude execSync origins ship in npm 2.0.13 gitHead; 2.0.14 gitHead is the execFileSync fix. No matching git tags. Side-branch gitHead ancestry is not used as a substitute for npm gitHead.",
        49: "Initial Claude commit created entity-scoped DynamoDB PKs. Hypothesized minimum 9f66c42f is later shard selection. GHSA names 481ce44d after a long pre-shard series; 94a129ae is the PK migration. Origin real, minimum-fix KEEP refused.",
        57: "Claude Code adds message_id.strip directory join plus rmtree. No repo GHSA; global CVE GHSA plus named fix commit. v1.1.0 / 1.3.4.",
        63: "Claude OAuth refresh interpolates tokens into execSync security -w. 9dce3d8b switches that write to execFileSync. Human 66d7178f later removes remaining shell on find-generic-password.",
        65: "Missing top-level mechanism_key reconstructed as unescaped Feishu mention RegExp in stripBotMention. Upstream Claude 4286755f; openclaw import 2267d58a; fix 7e67ab75. Extra named commit is tests.",
        73: "Claude EventTemplateImporter overwrite preserves org_id without a caller org check. NVD-imported GHSA, no repo advisory, first-party fix commit 7c2200d1. v2.5.37 / v2.5.39.",
        81: "Claude commit explicitly skips device identity when a token is present. Fix requires sharedAuthOk. Distinct invariant from ordinal 23.",
        111: "Claude ARC broadcaster treats only REJECTED/DOUBLE_SPEND as failure. INVALID/MALFORMED/ORPHAN stay success. Security commit also patches unrelated P0s. Origin real, umbrella KEEP refused.",
        119: "Claude native prompt-image loader omits workspaceOnly. Candidate in v2026.2.23; fix first in v2026.2.24. Shared SHA with other image rows is not a duplicate.",
        135: "Repo GHSA (global 404) says the CVE-2026-33645 filename fix was not applied to public checkSum. Copilot 157386c8 is that incomplete rem. 70b5b35a alnum-filters checkSum in v1.5.3.",
        137: "Peeled v3.11.1 Claude patch uses require === false and leaves omit-require in scope-out. Human 01a7552 is not an ancestor of v3.11.1-3.11.3. Complete 86ab819f in v3.11.4.",
        147: "Claude fork-merge adds IPv4-only validateUrlSync at v2.47.4. Official range starts there. IPv6 family extension in v2.47.14.",
        161: "Claude swaps includes() for RegExp.test() in parse_str at v2.0.39. Official range starts there. Residual is overwriting RegExp.prototype.test until v3.0.25.",
        163: "Copilot LoopLimit in 7.0.0 does not edit ScriptArray.cs. GHSA array*int range starts at 3.0.0. Old sibling, not GHSA-level AI origin. Distinct from 167.",
        167: "Non-enforcing ExpressionDepthLimit is in 6.6.0 (b5ac4bf, 2026-03-19). Copilot f55280a0 (2026-03-21) extends array initializers with the same LogError-and-continue. Official range starts 6.6.0.",
        171: "Codex value-only control-char rejection in 3.1.49 is incomplete of config injection. Section/option newline closed in 3.1.50. Distinct from 179.",
        179: "Codex blame denylist has --output and omits --contents/-S. Repo GHSA (global 404). 3.1.58 / 3.1.59. Distinct from 171.",
        185: "Claude Tabler squash first writes data-person_name. Member is not a 7.5.1 ancestor. Later human escapeHtml is still wrong. 7.6.0 merge uses escapeAttribute and also patches two other GHSAs.",
    }
    for c in cases:
        lines += [f"### Ordinal {c['ordinal']} — {c['verdict']} ({c['case_id']})", "", summaries[c["ordinal"]], ""]
    lines += [
        "## Sources",
        "",
        "| Clone | HEAD | Date |",
        "|-------|------|------|",
    ]
    for name, (head, date) in HEADS.items():
        lines.append(f"| {name} | `{head}` | {date} |")
    lines += [
        "",
        f"Frozen ledger SHA-256 `{sha256_file(LEDGER)}`.",
        "",
        "Counterexample classes actively tested: old-bug preservation, remediation-as-origin, squash/merge attribution, later-human blame, insufficient fix, umbrella fix, alias duplicates, missing mechanism_key uniqueness.",
        "",
    ]
    return "\n".join(lines) + "\n"


def write_replay() -> str:
    return """# redbase-odd independent replay

Ledger: autoresearch/orchestrator-260813-fp211-canonical/ledger.jsonl
Filter: counting.fp211_released_publication_admitted == true
Parity: fp211_adjudication.ordinal % 2 == 1
Assigned: 19,23,27,39,43,49,57,63,65,73,81,111,119,135,137,147,161,163,167,171,179,185

Cache: /home/hanqing/.cache/ghsa200-worker-clones/redbase-odd
Clones: git clone https://github.com/<owner>/<repo>.git  (no /tmp; no sibling even-lane conclusions)

Advisory fetch:
  gh api advisories/<ghsa-lower>
  gh api repos/<owner>/<repo>/security-advisories/<ghsa-lower>

Per row:
  git -C <clone> show --format='%an %ae%n%s%n%b' -s <candidate>
  git -C <clone> merge-base --is-ancestor <sha> <vuln-tag>; echo $?
  git -C <clone> merge-base --is-ancestor <fix> <vuln-tag>; echo $?
  git -C <clone> merge-base --is-ancestor <fix> <fixed-tag>; echo $?
  git -C <clone> grep / show parent vs candidate for the named sink
  git -C <clone> blame <vuln-tag> -- <file>  (when blobs diverge)

Special:
  23,185: git fetch origin <member-sha> because members were missing from the default clone
  43: curl https://registry.npmjs.org/agentic-flow/2.0.13 and 2.0.14 for gitHead
  65: independent clone of https://github.com/m1heng/clawdbot-feishu.git for upstream 4286755f
  137: merge-base --is-ancestor 01a7552 v3.11.1  (not git tag --contains)

KEEP is a proposal only. No canonical edits, commit, reset, or clean.
"""


def main() -> None:
    cases = build_cases()
    assert [c["ordinal"] for c in cases] == ASSIGNED
    assert len(cases) == 22
    ids = [c["case_id"] for c in cases]
    assert all(i.startswith("GHSA-") for i in ids)
    assert len(set(ids)) == 22
    for c in cases:
        assert c["verdict"] in {"KEEP", "NARROW", "REJECT", "UNKNOWN", "BLOCKED"}
        assert c["language"] == "en"

    counts = Counter(c["verdict"] for c in cases)
    per = {str(c["ordinal"]): c["verdict"] for c in cases}

    cases_path = OUT / "cases.jsonl"
    text = "".join(json.dumps(c, ensure_ascii=True, sort_keys=True) + "\n" for c in cases)
    cases_path.write_text(text)

    result = {
        "schema_version": 1,
        "artifact_kind": "ghsa200_redteam_redbase_odd",
        "language": "en",
        "status": "REDTEAM_COMPLETE",
        "causal_admission": False,
        "note": NOTE,
        "assigned_ordinals": ASSIGNED,
        "assigned_count": 22,
        "parity": "fp211_adjudication.ordinal % 2 == 1",
        "filter": "counting.fp211_released_publication_admitted == true",
        "verdicts": {
            "KEEP": counts.get("KEEP", 0),
            "NARROW": counts.get("NARROW", 0),
            "REJECT": counts.get("REJECT", 0),
            "UNKNOWN": counts.get("UNKNOWN", 0),
            "BLOCKED": counts.get("BLOCKED", 0),
        },
        "per_ordinal": per,
        "inputs": {
            "ledger_path": "autoresearch/orchestrator-260813-fp211-canonical/ledger.jsonl",
            "ledger_sha256": sha256_file(LEDGER),
            "cases_jsonl_sha256": hashlib.sha256(text.encode()).hexdigest(),
        },
        "independent_sources": {
            name: {"clone": str(CACHE / "clones" / name), "head": head, "head_committer_date": date}
            for name, (head, date) in HEADS.items()
        },
        "blockers": [],
    }
    (OUT / "result.json").write_text(json.dumps(result, indent=2, ensure_ascii=True) + "\n")
    (OUT / "report.md").write_text(write_report(cases))
    (OUT / "replay.txt").write_text(write_replay())
    print("wrote", len(cases), "cases", dict(counts))
    print("cases sha", result["inputs"]["cases_jsonl_sha256"])


if __name__ == "__main__":
    main()
