#!/usr/bin/env python3
"""Emit this lane's contract outputs. Write-scope: this directory only."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
FREEZE = json.loads((HERE / "id_freeze.json").read_text())
INPUT_HASHES = FREEZE["input_hashes"]

GATES = (
    "identity_gate",
    "ai_hunk_gate",
    "topology_gate",
    "but_for_gate",
    "fix_reversal_gate",
    "release_gate",
    "uniqueness_gate",
)


def gates(**kwargs):
    out = {k: "NOT_EVALUATED" for k in GATES}
    out.update(kwargs)
    return out


def case(**kwargs):
    row = {
        "schema_version": 1,
        "lane": "herdr-260813-ghsa200-remediation",
        "worker_pass_is_proposal": True,
        "aliases": [],
        "candidate_set": [],
        "carrier_set": [],
        "minimum_fix_set": [],
        "vulnerable_release_evidence": None,
        "fixed_release_evidence": None,
        "first_party_sources": [],
        "ai_marker_evidence": [],
        "counterevidence": [],
        "replay_commands": [],
        "baseline_overlap": "absent_from_fp211_declared_and_publication_corpus",
        "contribution_class": "AI_INCOMPLETE_REMEDIATION",
        "mechanism_key": None,
        "scope_statement": None,
        "notes": None,
    }
    row.update(kwargs)
    if "gates" in row:
        g = row.pop("gates")
        row.update(g)
    return row


CROSS = [
    case(
        case_id="GHSA-VH5J-5FHQ-9XWG",
        aliases=[],
        repository="taylored-ai/taylored",
        fp211_ordinal=84,
        fp211_verdict="UNKNOWN",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        mechanism_key=None,
        scope_statement="Preserve fp211 UNKNOWN: Jules 57b76343 SELECT-then-UPDATE get-patch race; human fdf67a6f closer; claimed 8.1.2/8.1.3 tags were not recovered.",
        disposition="CROSS_REVIEW_ONLY",
        verdict="UNKNOWN",
        upgrade_lane="herdr-260813-ghsa200-upgrade-a",
        recommendation="Do not upgrade to PASS without recovered 8.1.2 and 8.1.3 artifacts. Same SHA is a fix in ordinal 56 and a candidate here; keep opposite-role topology explicit.",
        baseline_overlap="fp211_public_case",
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="PASS",
            release_gate="UNKNOWN",
            uniqueness_gate="PASS",
        ),
        first_party_sources=["fp211 public_cases.jsonl ordinal 84", "fp211 final_mechanisms.jsonl ordinal 84"],
        counterevidence=["Local and remote tags do not include 8.1.2/8.1.3"],
        replay_commands=[
            "python3 -c \"import json;from pathlib import Path;print([r for r in Path('autoresearch/orchestrator-260813-fp211-audit/public_cases.jsonl').read_text().splitlines() if 'GHSA-VH5J-5FHQ-9XWG' in r][0][:400])\""
        ],
    ),
    case(
        case_id="GHSA-5WP8-Q9MX-8JX8",
        repository="qhkm/zeptoclaw",
        fp211_ordinal=126,
        fp211_verdict="NARROW",
        mechanism_key=None,
        scope_statement="Preserve fp211 NARROW zeptoclaw shell-filter incomplete rem.",
        disposition="CROSS_REVIEW_ONLY",
        verdict="NARROW",
        upgrade_lane="herdr-260813-ghsa200-upgrade-b",
        recommendation="Leave to upgrade-b. This lane does not propose PASS for an existing fp211 identity.",
        baseline_overlap="fp211_public_case",
        gates=gates(identity_gate="PASS", uniqueness_gate="PASS"),
        first_party_sources=["fp211 public_cases.jsonl ordinal 126"],
    ),
    case(
        case_id="GHSA-F38V-77QJ-H4JQ",
        aliases=["CVE-2026-57148"],
        repository="MervinPraison/PraisonAI",
        fp211_ordinal=169,
        fp211_verdict="NARROW",
        mechanism_key="praisonai-platform-jwt-default-open-guard-residual",
        scope_statement="Preserve fp211 NARROW JWT default-open residual. Release wording remains the NARROW axis versus PyPI 0.1.4/0.1.6.",
        disposition="CROSS_REVIEW_ONLY",
        verdict="NARROW",
        upgrade_lane="herdr-260813-ghsa200-upgrade-b",
        recommendation="Upgrade-b may close release_gate only with first-party GHSA version text plus recovered PyPI artifacts. Do not treat a later PraisonAI auth commit as a new rem PASS in this lane.",
        baseline_overlap="fp211_public_case",
        gates=gates(identity_gate="PASS", uniqueness_gate="PASS", release_gate="NARROW"),
        first_party_sources=["fp211 public_cases.jsonl ordinal 169"],
    ),
    case(
        case_id="GHSA-V396-V7Q4-X2QJ",
        repository="gitpython-developers/GitPython",
        fp211_ordinal=170,
        fp211_verdict="NARROW",
        mechanism_key=None,
        scope_statement="Preserve fp211 NARROW joined-short-option residual. Tags 3.1.47-3.1.50 exist; GHSA wording that names only 3.1.50 is the NARROW axis.",
        disposition="CROSS_REVIEW_ONLY",
        verdict="NARROW",
        upgrade_lane="herdr-260813-ghsa200-upgrade-b",
        recommendation="Replay tag --contains c9a26789 --no-contains 181e8ede shows 3.1.47-3.1.50. Upgrade-b should reconcile advisory version text before any CONFIRM. Sibling GitPython residuals stay uniqueness-sensitive.",
        baseline_overlap="fp211_public_case",
        gates=gates(identity_gate="PASS", uniqueness_gate="NARROW", release_gate="NARROW"),
        first_party_sources=["fp211 public_cases.jsonl ordinal 170"],
        replay_commands=[
            "git -C /tmp/ghsa200-worker-clones/remediation/GitPython tag --contains c9a26789 --no-contains 181e8ede --sort=version:refname"
        ],
    ),
    case(
        case_id="GHSA-3WXW-XV34-2FRG",
        repository="gitpython-developers/GitPython",
        fp211_ordinal=180,
        fp211_verdict="NARROW",
        mechanism_key=None,
        scope_statement="Preserve fp211 NARROW positional --file residual. Uniqueness versus GHSA-3F7W remains the NARROW axis.",
        disposition="CROSS_REVIEW_ONLY",
        verdict="NARROW",
        upgrade_lane="herdr-260813-ghsa200-upgrade-b",
        recommendation="Do not count a second GitPython option-guard residual as a fresh rem PASS. Upgrade-b owns uniqueness versus GHSA-3F7W-8RR8-F37F.",
        baseline_overlap="fp211_public_case",
        gates=gates(identity_gate="PASS", uniqueness_gate="NARROW"),
        first_party_sources=["fp211 public_cases.jsonl ordinal 180"],
    ),
    case(
        case_id="GHSA-F2FQ-4RMP-9X8C",
        repository="ChurchCRM/CRM",
        fp211_ordinal=186,
        fp211_verdict="NARROW",
        mechanism_key="churchcrm-2fa-failure-counter-residual",
        scope_statement="Preserve fp211 NARROW ChurchCRM 2FA failure-counter residual.",
        disposition="CROSS_REVIEW_ONLY",
        verdict="NARROW",
        upgrade_lane="herdr-260813-ghsa200-upgrade-b",
        recommendation="Leave to upgrade-b. No new rem PASS.",
        baseline_overlap="fp211_public_case",
        gates=gates(identity_gate="PASS"),
        first_party_sources=["fp211 public_cases.jsonl ordinal 186"],
    ),
    case(
        case_id="GHSA-PV2J-RGHR-V5R9",
        aliases=["CVE-2026-57120"],
        repository="MervinPraison/PraisonAI",
        fp211_ordinal=188,
        fp211_verdict="NARROW",
        mechanism_key="praisonai-python-sandbox-format-resolver-bypass",
        scope_statement="Preserve fp211 NARROW Python sandbox format-resolver bypass.",
        disposition="CROSS_REVIEW_ONLY",
        verdict="NARROW",
        upgrade_lane="herdr-260813-ghsa200-upgrade-b",
        recommendation="Leave to upgrade-b. Later PraisonAI sandbox advisories in this lane were rejected as sibling-unattempted or human-authored.",
        baseline_overlap="fp211_public_case",
        gates=gates(identity_gate="PASS"),
        first_party_sources=["fp211 public_cases.jsonl ordinal 188"],
    ),
]

for cid, ord_, key, stmt in [
    ("GHSA-3FP5-V549-9V66", 189, "openclaw-flock-wrapper-approval-binding-residual", "flock wrapper approval-binding residual"),
    ("GHSA-2X93-H3HG-2XFP", 192, "openclaw-browser-snapshot-current-tab-preflight-residual", "browser snapshot current-tab preflight residual"),
    ("GHSA-QJPC-QF9M-XWMR", 194, "openclaw-trusted-proxy-unpaired-scope-residual", "trusted-proxy unpaired-scope residual"),
    ("GHSA-9C3V-684M-579C", 195, "openclaw-mcp-sse-redirect-header-residual", "MCP SSE redirect-header residual"),
    ("GHSA-J4CX-JVQ7-79VM", 196, "openclaw-trajectory-export-redaction-residual", "trajectory export redaction residual"),
    ("GHSA-WP73-F3GG-W4VR", 197, "openclaw-clickclack-toolsallow-propagation-residual", "clickclack toolsAllow propagation residual"),
    ("GHSA-7JX6-764P-FGG9", 198, "openclaw-qqbot-same-chat-approval-fallback", "qqbot same-chat approval fallback"),
    ("GHSA-2HFG-4FH4-QP7F", 199, "openclaw-browser-action-kind-navigation-coverage-residual", "browser action-kind navigation coverage residual"),
]:
    CROSS.append(
        case(
            case_id=cid,
            repository="openclaw/openclaw",
            fp211_ordinal=ord_,
            fp211_verdict="NARROW",
            mechanism_key=key,
            scope_statement=f"Preserve fp211 NARROW {stmt}.",
            disposition="CROSS_REVIEW_ONLY",
            verdict="NARROW",
            upgrade_lane="herdr-260813-ghsa200-upgrade-b",
            recommendation="Leave to upgrade-b. This lane does not re-propose openclaw residuals already in the fp211 publication corpus.",
            baseline_overlap="fp211_public_case",
            gates=gates(identity_gate="PASS", uniqueness_gate="PASS"),
            first_party_sources=[f"fp211 public_cases.jsonl ordinal {ord_}"],
        )
    )

NEW = [
    case(
        case_id="GHSA-89CF-6HMV-8RXM",
        repository="scriban/scriban",
        mechanism_key="scriban-scriptrange-multiply-looplimit-bypass",
        scope_statement="ScriptRange.Multiply bypasses LoopLimit after the ScriptArray multiply fix for already-counted GHSA-Q6RR-FM2G-G5X8.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="same_mechanism_series_and_preexisting_sibling",
        candidate_set=["2d01bd15a1114fac2533aa005036e07389ee89db"],
        minimum_fix_set=["973edd1f1c10fae7d3a8650ac0d309d52072102c"],
        vulnerable_release_evidence={"advisory_range": ">= 3.0.0, <= 7.2.5", "human_partial": "205ca6a7c2349d3d388bd5f1f7729ee198c0d5e5 first tag 7.2.1"},
        fixed_release_evidence={"advisory_patched": "7.2.6", "closer_first_tag": "7.2.6"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="NARROW",
            topology_gate="PASS",
            but_for_gate="REJECT",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="REJECT",
        ),
        first_party_sources=["https://github.com/scriban/scriban/security/advisories/GHSA-89cf-6hmv-8rxm"],
        ai_marker_evidence=["2d01bd15 Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com> hardens expression bounds and array.join LimitToString, not ScriptRange.Multiply"],
        counterevidence=[
            "First-party advisory names itself the incomplete fix of GHSA-q6rr-fm2g-g5x8, which is already an fp211 CONFIRM",
            "205ca6a7 and 973edd1f are Alexandre Mutel with no AI trailer; 205ca6a7 closed ScriptArray only",
            "ScriptRange.Multiply unbounded form exists in the parent of the Copilot attempt; deleting 2d01bd15 restores the broader old LoopLimit gap without creating this named residual",
        ],
        replay_commands=[
            "git -C /tmp/ghsa200-worker-clones/remediation/scriban show -s --format='%an %s%n%b' 2d01bd15a1114fac2533aa005036e07389ee89db",
            "git -C /tmp/ghsa200-worker-clones/remediation/scriban show -s --format='%an %s' 205ca6a7 973edd1f",
        ],
    ),
    case(
        case_id="GHSA-24C8-4792-22HX",
        repository="scriban/scriban",
        mechanism_key="scriban-array-insert-at-unbounded-fill",
        scope_statement="ArrayFunctions.InsertAt fill loop never received the LoopLimit overload that dde661d applied to sibling ArrayFunctions methods.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="wrong_edge_preexisting_sibling",
        candidate_set=["dde661d36bb6b06414546c6b1272fc1b517078c9"],
        minimum_fix_set=["7fdf19df7db01c5e57888c5cc31e4d05f3d75440"],
        vulnerable_release_evidence={"advisory_range": "<= 7.1.0", "candidate_first_tag": "7.0.0"},
        fixed_release_evidence={"advisory_patched": "7.2.0", "closer_first_tag": "7.2.0"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="REJECT",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="NARROW",
        ),
        first_party_sources=["https://github.com/scriban/scriban/security/advisories/GHSA-24c8-4792-22hx"],
        ai_marker_evidence=["dde661d Co-authored-by: Copilot; 157-line ArrayFunctions.cs sweep; InsertAt body unchanged versus parent"],
        counterevidence=[
            "Parent of dde661d already contains unbounded InsertAt in the same form",
            "dde661d never edited InsertAt; deleting the AI sweep leaves InsertAt identical",
            "This is the fp211 sibling-unguarded lesson, not a residual created by the AI attempt",
        ],
        replay_commands=[
            "git -C /tmp/ghsa200-worker-clones/remediation/scriban show -s --format='%s%n%b' dde661d36bb6b06414546c6b1272fc1b517078c9",
            "git -C /tmp/ghsa200-worker-clones/remediation/scriban show dde661d^:src/Scriban/Functions/ArrayFunctions.cs | rg -n InsertAt",
            "git -C /tmp/ghsa200-worker-clones/remediation/scriban tag --contains dde661d --sort=version:refname | head",
            "git -C /tmp/ghsa200-worker-clones/remediation/scriban tag --contains 7fdf19d --sort=version:refname | head",
        ],
    ),
    case(
        case_id="GHSA-C875-H985-HVRC",
        repository="scriban/scriban",
        mechanism_key="scriban-builtin-looplimit-bypass",
        scope_statement="Original builtin LoopLimit bypass patched in 7.0.0. Copilot dde661d is the closer, not an incomplete rem of a later residual.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="ai_as_fixer_not_residual_author",
        candidate_set=[],
        minimum_fix_set=["dde661d36bb6b06414546c6b1272fc1b517078c9"],
        vulnerable_release_evidence={"advisory_range": "<= 6.6.0"},
        fixed_release_evidence={"advisory_patched": "7.0.0"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="REJECT",
            topology_gate="PASS",
            but_for_gate="REJECT",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="NARROW",
        ),
        first_party_sources=["https://github.com/scriban/scriban/security/advisories/GHSA-c875-h985-hvrc"],
        counterevidence=["AI marker is on the 7.0.0 closer, not on a prior security attempt that created a new residual form"],
        replay_commands=["git -C /tmp/ghsa200-worker-clones/remediation/scriban show -s --format='%s%n%b' dde661d"],
    ),
    case(
        case_id="GHSA-P6Q4-FGR8-VX4P",
        repository="scriban/scriban",
        mechanism_key="scriban-nested-array-initializer-depth",
        scope_statement="Nested array-initializer recursion missed by a prior ExpressionDepthLimit fix. Patched in the same 7.0.0 wave as the named predecessor.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="wrong_edge_and_same_first_tag",
        candidate_set=[],
        minimum_fix_set=[],
        vulnerable_release_evidence={"advisory_range": "<= 6.6.0"},
        fixed_release_evidence={"advisory_patched": "7.0.0"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="UNKNOWN",
            topology_gate="UNKNOWN",
            but_for_gate="REJECT",
            fix_reversal_gate="PASS",
            release_gate="NARROW",
            uniqueness_gate="NARROW",
        ),
        first_party_sources=["https://github.com/scriban/scriban/security/advisories/GHSA-p6q4-fgr8-vx4p"],
        counterevidence=[
            "Named residual is a sibling parser path the prior depth-limit commit did not edit",
            "Vulnerable and patched bounds are the 6.6.0 / 7.0.0 pair; no released residual window after an AI rem was proven",
        ],
    ),
    case(
        case_id="GHSA-WVPP-8HX9-P66J",
        repository="gitpython-developers/GitPython",
        mechanism_key="gitpython-option-candidates-unsplit-short-value-smuggle",
        scope_statement="split_single_char_options=False joined short-option value smuggling after e8d0fbf7, which is the published closer of already-counted GHSA-R9MR-M37C-5FR3.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="same_mechanism_series",
        candidate_set=["e8d0fbf774d1f6baa3b481adfe48bd262e43b453"],
        minimum_fix_set=["96a888f4d782cb2f80452148e48e60ce4af6d541"],
        vulnerable_release_evidence={"advisory_range": "<= 3.1.57", "candidate_first_tag": "3.1.54"},
        fixed_release_evidence={"advisory_patched": ">= 3.1.58", "closer_first_tag": "3.1.58"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="NARROW",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="REJECT",
        ),
        first_party_sources=["https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-wvpp-8hx9-p66j"],
        ai_marker_evidence=["e8d0fbf7 Author: GPT 5.6 <codex@openai.com>; Refs GHSA-r9mr-m37c-5fr3; explicitly preserves the non-splitting compatibility path"],
        counterevidence=[
            "e8d0fbf7 is the complete fix of fp211-counted R9MR, not a novel rem series",
            "Same _option_candidates / check_unsafe_options value-smuggling invariant as R9MR",
            "96a888f4 closer is Byron with GPT 5.6 co-author; carrier does not create a new countable case",
        ],
        replay_commands=[
            "git -C /tmp/ghsa200-worker-clones/remediation/GitPython show -s --format='%an %ae %s%n%b' e8d0fbf774d1f6baa3b481adfe48bd262e43b453",
            "git -C /tmp/ghsa200-worker-clones/remediation/GitPython tag --contains e8d0fbf7 --sort=version:refname | head",
            "git -C /tmp/ghsa200-worker-clones/remediation/GitPython tag --contains 96a888f4 --sort=version:refname | head",
        ],
    ),
    case(
        case_id="GHSA-2F96-G7MH-G2HX",
        repository="gitpython-developers/GitPython",
        mechanism_key="gitpython-long-option-prefix-abbreviation",
        scope_statement="git long-option prefix abbreviation bypass of the 3.1.47 exact-match denylist (advisory names GHSA-rpm5 / CVE-2026-42215).",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="same_denylist_series_commit_only_window",
        candidate_set=["c9a26789d88b18f8b4620f37307df2976292d2a0"],
        minimum_fix_set=["181e8ede7543dbbdcee92756cea260f675316c63"],
        vulnerable_release_evidence={"advisory_range": "<= 3.1.50", "denylist_first_tag": "3.1.47"},
        fixed_release_evidence={"advisory_patched": ">= 3.1.51", "closer_first_tag": "3.1.51"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="NARROW",
            topology_gate="PASS",
            but_for_gate="NARROW",
            fix_reversal_gate="PASS",
            release_gate="REJECT",
            uniqueness_gate="REJECT",
        ),
        first_party_sources=["https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-2f96-g7mh-g2hx"],
        ai_marker_evidence=["181e8ede and 56806080 are GPT 5.6; both first appear in tag 3.1.51, which is the patched bound"],
        counterevidence=[
            "Prefix residual is a leftover of the already-counted 3.1.47 denylist / V396 window, not a new rem created by 181e8ede",
            "181e8ede is the published closer and shares first tag 3.1.51 with 56806080; no commit-distinct released residual window for those GPT hunks",
            "Parent GHSA-rpm5-65cw-6hj4 is absent from fp211, but the denylist mechanism is already counted via V396 / R9MR family",
        ],
        replay_commands=[
            "git -C /tmp/ghsa200-worker-clones/remediation/GitPython tag --contains c9a26789 --no-contains 181e8ede --sort=version:refname",
            "git -C /tmp/ghsa200-worker-clones/remediation/GitPython tag --contains 181e8ede --sort=version:refname | head",
        ],
    ),
    case(
        case_id="GHSA-X2QX-6953-8485",
        aliases=["CVE-2026-42284"],
        repository="gitpython-developers/GitPython",
        mechanism_key="gitpython-multi-options-presplit-check",
        scope_statement="Original multi_options checked before shlex.split. c9a26789 is the closer of this original bug, not a residual of a later AI rem.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="original_vuln_not_residual",
        candidate_set=[],
        minimum_fix_set=["c9a26789d88b18f8b4620f37307df2976292d2a0"],
        vulnerable_release_evidence={"advisory_range": "<= 3.1.44"},
        fixed_release_evidence={"advisory_patched": ">=3.1.47", "closer_first_tag": "3.1.47"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="REJECT",
            topology_gate="PASS",
            but_for_gate="REJECT",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="NARROW",
        ),
        first_party_sources=["https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-x2qx-6953-8485"],
        counterevidence=["This is the pre-split original; V396 already counts the later joined-short residual of the same denylist"],
    ),
    case(
        case_id="GHSA-956X-8GVW-WG5V",
        repository="gitpython-developers/GitPython",
        mechanism_key="gitpython-unguarded-archive-ls-remote-blame",
        scope_statement="Original unguarded archive/ls_remote/blame. 701ce32f is the GPT closer of this named scope; later residuals are already counted.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="ai_as_fixer_residuals_already_counted",
        candidate_set=[],
        minimum_fix_set=["701ce32fe5ba8cb622c0e0342a376a6beb47d738"],
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="REJECT",
            topology_gate="PASS",
            but_for_gate="REJECT",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="REJECT",
        ),
        first_party_sources=["https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-956x-8gvw-wg5v"],
        ai_marker_evidence=["701ce32f Author: GPT 5.6; this SHA is the closer of the named original, not a residual-creating rem"],
        counterevidence=["Later option-guard residuals of this denylist are already in fp211 (R9MR, V396, 3WXW, 94P4 family)"],
    ),
    case(
        case_id="GHSA-RWJ8-PGH3-R573",
        repository="gitpython-developers/GitPython",
        mechanism_key="gitpython-clone-from-expandvars",
        scope_statement="clone_from expandvars. 8ac5a305 is the GPT complete fix of this named scope; sibling residual already counted as GHSA-94P4-4CQ8-9G67.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="complete_fix_of_named_scope",
        candidate_set=[],
        minimum_fix_set=["8ac5a30519b6f4af85398b9b9d7064ff4d452da2"],
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="REJECT",
            topology_gate="PASS",
            but_for_gate="REJECT",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="REJECT",
        ),
        first_party_sources=["https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-rwj8-pgh3-r573"],
        ai_marker_evidence=["8ac5a305 Author: GPT 5.6; closer of this scope"],
        counterevidence=["Sibling expandvars residual already counted as GHSA-94P4-4CQ8-9G67"],
    ),
    case(
        case_id="GHSA-9QHQ-V63V-FV3J",
        aliases=["CVE-2026-41497"],
        repository="MervinPraison/PraisonAI",
        mechanism_key="praisonai-mcp-parse-command-no-allowlist",
        scope_statement="Advisory names 47bff654 as the incomplete MCP command-validation fix that still has no allowlist.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="human_incomplete_fix",
        candidate_set=["47bff65413beaa3c21bf633c1fae4e684348368c"],
        minimum_fix_set=[],
        vulnerable_release_evidence={"advisory_range": "<= 4.6.8"},
        fixed_release_evidence={"advisory_patched": ">= 4.6.9"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="REJECT",
            topology_gate="PASS",
            but_for_gate="REJECT",
            fix_reversal_gate="NARROW",
            release_gate="NARROW",
            uniqueness_gate="PASS",
        ),
        first_party_sources=["https://github.com/MervinPraison/PraisonAI/security/advisories/GHSA-9qhq-v63v-fv3j"],
        counterevidence=[
            "47bff654 author Mervin Praison; body has no Co-authored-by / Copilot / Claude / GPT trailer",
            "Advisory itself says the named fix still lacks an allowlist, so fix_reversal is also incomplete",
        ],
        replay_commands=[
            "git -C /tmp/ghsa200-worker-clones/remediation/PraisonAI show -s --format='%an %ae %s%n%b' 47bff65413beaa3c21bf633c1fae4e684348368c"
        ],
    ),
    case(
        case_id="GHSA-RG3H-X3JW-7JM5",
        aliases=["CVE-2026-41496"],
        repository="MervinPraison/PraisonAI",
        mechanism_key="praisonai-table-prefix-sqli-sibling-backends",
        scope_statement="SQLite table_prefix guard left nine sibling conversation-store backends unguarded.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="wrong_edge_sibling_unattempted",
        candidate_set=[],
        minimum_fix_set=[],
        vulnerable_release_evidence={"advisory_range": "praisonai <= 4.6.8"},
        fixed_release_evidence={"advisory_patched": ">= 4.6.9"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="UNKNOWN",
            topology_gate="UNKNOWN",
            but_for_gate="REJECT",
            fix_reversal_gate="NARROW",
            release_gate="NARROW",
            uniqueness_gate="PASS",
        ),
        first_party_sources=["https://github.com/MervinPraison/PraisonAI/security/advisories/GHSA-rg3h-x3jw-7jm5"],
        counterevidence=[
            "Classic sibling-unattempted: the named residual lives in backends the SQLite-only fix never edited",
            "Deleting that SQLite guard restores the broader old SQLite injection; it does not create the MySQL/Postgres residual",
        ],
    ),
    case(
        case_id="GHSA-JXCW-QP4H-6JFQ",
        aliases=["CVE-2026-57146"],
        repository="MervinPraison/PraisonAI",
        mechanism_key="praisonai-a2u-cli-default-open-after-claimed-fix",
        scope_statement="praisonai serve a2u remains unauthenticated by default after claimed GHSA-F292-66H9-FPMF fix in 4.5.115.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="human_claimed_fix_unattempted_cli_path",
        candidate_set=[],
        minimum_fix_set=[],
        vulnerable_release_evidence={"advisory_range": ">= 4.5.115, <= 4.6.58"},
        fixed_release_evidence={"advisory_patched": ">= 4.6.61"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="REJECT",
            topology_gate="NARROW",
            but_for_gate="REJECT",
            fix_reversal_gate="NARROW",
            release_gate="NARROW",
            uniqueness_gate="PASS",
        ),
        first_party_sources=["https://github.com/MervinPraison/PraisonAI/security/advisories/GHSA-jxcw-qp4h-6jfq"],
        counterevidence=[
            "v4.5.115 release commit ed3a689f and harden bump b1048da6 are MervinPraison with no AI trailer",
            "CLI path never received the unified API-key middleware; residual is unattempted sibling, not an AI-created bypass",
            "Later praisonai-triage-agent[bot] A2U commits b12b2b68 / 86dd01a0 first appear in v4.6.161, after the advisory patched bound",
        ],
        replay_commands=[
            "git -C /tmp/ghsa200-worker-clones/remediation/PraisonAI show -s --format='%an %s' ed3a689f b1048da6",
            "git -C /tmp/ghsa200-worker-clones/remediation/PraisonAI tag --contains b12b2b68 --sort=version:refname | head",
        ],
    ),
    case(
        case_id="GHSA-892R-P3JQ-JP24",
        aliases=["CVE-2026-57116"],
        repository="MervinPraison/PraisonAI",
        mechanism_key="praisonai-agentos-unauth-after-pm96",
        scope_statement="AgentOS /api/chat remains unauthenticated after claimed GHSA-PM96-6XPR-978X patched version 4.5.128.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="sibling_surface_never_attempted",
        candidate_set=[],
        minimum_fix_set=["b4270173"],
        vulnerable_release_evidence={"advisory_range": ">= 4.2.1, <= 4.6.57"},
        fixed_release_evidence={"advisory_patched": ">= 4.6.59", "closer_first_tag": "v4.6.59"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="REJECT",
            topology_gate="PASS",
            but_for_gate="REJECT",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
        ),
        first_party_sources=["https://github.com/MervinPraison/PraisonAI/security/advisories/GHSA-892r-p3jq-jp24"],
        counterevidence=[
            "Closer b4270173 feat(auth) AgentOS middleware is MervinPraison with no AI trailer",
            "AgentOS never received the generated-deploy API auth path; residual is sibling-unattempted",
        ],
        replay_commands=[
            "git -C /tmp/ghsa200-worker-clones/remediation/PraisonAI show -s --format='%an %s%n%b' b4270173"
        ],
    ),
    case(
        case_id="GHSA-JXX9-PX88-PJ69",
        aliases=["CVE-2026-45707"],
        repository="czlonkowski/n8n-mcp",
        mechanism_key="n8n-mcp-multitenant-env-credential-fallback",
        scope_statement="ENABLE_MULTI_TENANT requests without tenant headers fall back to process-level N8N_API_URL/N8N_API_KEY.",
        contribution_class="AI_NEW_SURFACE_CONTRIBUTOR",
        disposition="ROUTE_FRESH_AM",
        verdict="REJECT",
        false_positive_class="wrong_contribution_class_for_this_lane",
        candidate_set=["f237fad1e84fbeef388c552c265e61a640352c92"],
        carrier_set=["853015d0897be7cf2d9d4726de195c938e4395ab"],
        minimum_fix_set=["853015d0897be7cf2d9d4726de195c938e4395ab"],
        vulnerable_release_evidence={"advisory_range": "<= 2.51.1", "feature_first_tag": "v2.12.1"},
        fixed_release_evidence={"advisory_patched": "2.51.2", "closer_first_tag": "v2.51.2"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="PASS",
            topology_gate="NARROW",
            but_for_gate="NARROW",
            fix_reversal_gate="PASS",
            release_gate="PASS",
            uniqueness_gate="PASS",
        ),
        first_party_sources=["https://github.com/czlonkowski/n8n-mcp/security/advisories/GHSA-jxx9-px88-pj69"],
        ai_marker_evidence=[
            "f237fad feat: implement multi-tenant support; Generated with Claude Code; Co-Authored-By: Claude <noreply@anthropic.com>"
        ],
        counterevidence=[
            "This is a new multi-tenant feature with fail-open fallback, not an AI security attempt that left a residual of a prior vulnerability",
            "Deleting f237fad removes the named fallback because it removes the whole surface; that is origin / new-surface but-for, owned by fresh-am (owner C)",
            "Distinct from already-counted n8n-mcp IPv6 SSRF GHSA-56C3-VFP2-5QQJ",
            "853015d is a merge-from-fork carrier; fresh-am must resolve the atomic fix member before any PASS",
        ],
        replay_commands=[
            "git -C /tmp/ghsa200-worker-clones/remediation/n8n-mcp show -s --format='%H %an %s%n%b' f237fad",
            "git -C /tmp/ghsa200-worker-clones/remediation/n8n-mcp tag --contains f237fad --sort=version:refname | head",
            "git -C /tmp/ghsa200-worker-clones/remediation/n8n-mcp tag --contains 853015d --sort=version:refname | head",
        ],
        notes="Dedupe by contribution_class: this lane will not propose PASS. Fresh-am may evaluate AI_NEW_SURFACE / AI_DIRECT_ROOT independently.",
    ),
    case(
        case_id="GHSA-6CQF-375W-639G",
        aliases=["CVE-2026-50105"],
        repository="go-gitea/gitea",
        mechanism_key="gitea-feed-token-scope-bypass",
        scope_statement="RSS/Atom feed handlers omit the token-scope checks that PR #37698 added to download handlers.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="human_pr_sibling_unattempted",
        candidate_set=[],
        minimum_fix_set=[],
        vulnerable_release_evidence={"advisory_range": "<= 1.26.4"},
        fixed_release_evidence={"advisory_patched": "1.27.0"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="REJECT",
            topology_gate="UNKNOWN",
            but_for_gate="REJECT",
            fix_reversal_gate="UNKNOWN",
            release_gate="UNKNOWN",
            uniqueness_gate="PASS",
        ),
        first_party_sources=["https://github.com/go-gitea/gitea/security/advisories/GHSA-6cqf-375w-639g"],
        counterevidence=[
            "Named incomplete attempt is human PR #37698 on download handlers; feeds were never edited",
            "No AI-authored atomic rem of the feed surface was recovered; gitea was not cloned because the advisory already fails the rem creation test",
        ],
    ),
    case(
        case_id="GHSA-Q9P7-WQXG-MRHC",
        aliases=["CVE-2026-54769"],
        repository="langroid/langroid",
        mechanism_key="langroid-eval-empty-locals-builtins-leak",
        scope_statement="eval(code, vars, {}) still exposes builtins. fp211 already counts GHSA-X34R-63HX-W57F for a Copilot full_eval flip on a related eval path.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="human_sandbox_design_not_ai_residual",
        candidate_set=[],
        minimum_fix_set=[],
        vulnerable_release_evidence={"advisory_range": "<= 0.65.1"},
        fixed_release_evidence={"advisory_patched": "0.65.2"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="REJECT",
            topology_gate="UNKNOWN",
            but_for_gate="REJECT",
            fix_reversal_gate="UNKNOWN",
            release_gate="UNKNOWN",
            uniqueness_gate="NARROW",
        ),
        first_party_sources=["https://github.com/langroid/langroid/security/advisories/GHSA-q9p7-wqxg-mrhc"],
        counterevidence=[
            "Named residual is the empty-locals eval pattern, a human sanitizer design, not a residual created by the Copilot full_eval hunk counted in X34R",
            "No atomic AI marker was recovered on eval(code, vars, {})",
        ],
    ),
    case(
        case_id="GHSA-62Q4-447F-WV8H",
        aliases=["CVE-2026-46338"],
        repository="facelessuser/pymdown-extensions",
        mechanism_key="pymdown-snippets-sibling-prefix-reintro",
        scope_statement="PR #2039 / 7c13bda5 (2023-05-15) replaced samefile containment with startswith, reintroducing sibling-prefix traversal.",
        contribution_class="AI_REINTRODUCTION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="no_ai_marker_pre_coverage",
        candidate_set=["7c13bda5b7793b172efd1abb6712e156a83fe07d"],
        minimum_fix_set=[],
        vulnerable_release_evidence={"advisory_range": ">= 10.0.1, <= 10.21.2"},
        fixed_release_evidence={"advisory_patched": "10.21.3"},
        gates=gates(
            identity_gate="PASS",
            ai_hunk_gate="REJECT",
            topology_gate="PASS",
            but_for_gate="NARROW",
            fix_reversal_gate="UNKNOWN",
            release_gate="PASS",
            uniqueness_gate="PASS",
        ),
        first_party_sources=["https://github.com/facelessuser/pymdown-extensions/security/advisories/GHSA-62q4-447f-wv8h"],
        counterevidence=[
            "Reintroduction commit is 2023-05-15, before May 2025 coverage",
            "No explicit AI marker was recovered on 7c13bda5 from the first-party advisory text",
        ],
    ),
    case(
        case_id="GHSA-P8RR-9CVG-CX5J",
        aliases=["CVE-2026-59101"],
        repository="EstrellaXD/Auto_Bangumi",
        mechanism_key="autobangumi-setup-test-downloader-ssrf",
        scope_statement="Claude-authored 61ff20fe re-allows private/loopback setup URLs after a prior guard; published 3.2.8 closer 487bdfec still allows private/loopback.",
        contribution_class="AI_REINTRODUCTION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="unreviewed_identity_and_insufficient_fix",
        candidate_set=["61ff20fef663aaac88add4f5d72fd560ed6d2abd"],
        minimum_fix_set=["487bdfec545e805ae416e6ddf28651bd274d6a73"],
        vulnerable_release_evidence={"reintro_first_tags": ["3.2.5", "3.2.6"]},
        fixed_release_evidence={"claimed_tag": "3.2.8", "closer_comment": "Private/loopback IPs stay allowed"},
        gates=gates(
            identity_gate="REJECT",
            ai_hunk_gate="PASS",
            topology_gate="PASS",
            but_for_gate="PASS",
            fix_reversal_gate="REJECT",
            release_gate="NARROW",
            uniqueness_gate="PASS",
        ),
        first_party_sources=["https://github.com/advisories/GHSA-p8rr-9cvg-cx5j"],
        ai_marker_evidence=[
            "61ff20fe Co-Authored-By: Claude Opus 4.6 <noreply@anthropic.com> allow private IPs in setup",
            "5382aec8 Generated with Claude Code; origin of the setup wizard HTTP surface (origin class, not counted here)",
            "487bdfec Co-Authored-By: Claude Fable 5; published closer still documents private/loopback as allowed",
        ],
        counterevidence=[
            "GitHub global advisory type is unreviewed; repo first-party GHSA object was not recovered (404 on Auto-Bangumi and smartloli repo advisory APIs)",
            "487bdfec comment: Private/loopback IPs stay allowed (a LAN NAS is the normal case)",
            "Unreviewed NVD-style GHSA does not satisfy the first-party identity gate",
        ],
        replay_commands=[
            "gh api /advisories/GHSA-p8rr-9cvg-cx5j --jq '{type:.type,cve:.cve_id,summary:.summary}'",
            "git -C /home/hanqing/agents/ai-slop/.ai-slop/cache/cve-analyzer/repos/v2_github.com_auto_bangumi_4021d9210b67fb76e94527ac9a528c0c6d218abf93781a18189250ff2b9c4776 show -s --format='%s%n%b' 61ff20fef663aaac88add4f5d72fd560ed6d2abd",
            "git -C /home/hanqing/agents/ai-slop/.ai-slop/cache/cve-analyzer/repos/v2_github.com_auto_bangumi_4021d9210b67fb76e94527ac9a528c0c6d218abf93781a18189250ff2b9c4776 show 487bdfec | rg -n 'Private/loopback'",
        ],
    ),
    case(
        case_id="GHSA-239W-M3H6-CH8V",
        aliases=["CVE-2026-54094"],
        repository="filebrowser/filebrowser",
        mechanism_key="filebrowser-symlink-scope-escape",
        scope_statement="Global GHSA for symlink following outside filebrowser scope. Already-counted CVE-2026-55667/55668 cover File Browser symlink/scope family.",
        contribution_class="AI_INCOMPLETE_REMEDIATION",
        disposition="REJECT",
        verdict="REJECT",
        false_positive_class="wrong_class_and_likely_umbrella",
        candidate_set=[],
        minimum_fix_set=[],
        vulnerable_release_evidence={"advisory_range": "filebrowser/v2 <= 2.63.13"},
        fixed_release_evidence={"advisory_patched": "2.63.14"},
        gates=gates(
            identity_gate="NARROW",
            ai_hunk_gate="UNKNOWN",
            topology_gate="UNKNOWN",
            but_for_gate="UNKNOWN",
            fix_reversal_gate="UNKNOWN",
            release_gate="NARROW",
            uniqueness_gate="REJECT",
        ),
        first_party_sources=["https://github.com/advisories/GHSA-239w-m3h6-ch8v"],
        counterevidence=[
            "No rem/reintro proof recovered; owner F belongs to fresh-am if this is origin",
            "CVE-2026-55667 and CVE-2026-55668 are already in the fp211 declared corpus",
        ],
        notes="Not a rem PASS. Fresh-am may inspect only if the mechanism is distinct and AI-authored.",
    ),
]


def main():
    rows = CROSS + NEW
    # Stable order: cross-review by ordinal, then new by case_id
    cross = [r for r in rows if r["disposition"] == "CROSS_REVIEW_ONLY"]
    fresh = [r for r in rows if r["disposition"] != "CROSS_REVIEW_ONLY"]
    cross.sort(key=lambda r: r.get("fp211_ordinal") or 0)
    fresh.sort(key=lambda r: r["case_id"])
    ordered = cross + fresh

    (HERE / "cases.jsonl").write_text("".join(json.dumps(r, ensure_ascii=True) + "\n" for r in ordered))

    counts = {
        "reviewed_rows": len(ordered),
        "pass_proposals": sum(1 for r in ordered if r["verdict"] == "PASS"),
        "reject": sum(1 for r in ordered if r["verdict"] == "REJECT"),
        "narrow": sum(1 for r in ordered if r["verdict"] == "NARROW"),
        "unknown": sum(1 for r in ordered if r["verdict"] == "UNKNOWN"),
        "blocked": sum(1 for r in ordered if r["verdict"] == "BLOCKED"),
        "cross_review_only": sum(1 for r in ordered if r["disposition"] == "CROSS_REVIEW_ONLY"),
        "route_fresh": sum(1 for r in ordered if r["disposition"] == "ROUTE_FRESH_AM"),
        "new_ids_reviewed": len(fresh),
    }

    result = {
        "lane": "herdr-260813-ghsa200-remediation",
        "task": "fresh AI_INCOMPLETE_REMEDIATION and AI_REINTRODUCTION across all repositories",
        "status": "COMPLETE",
        "started_at": "2026-08-13T16:23:00-04:00",
        "ended_at": datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"),
        "output_dir": str(HERE),
        "clone_root": "/tmp/ghsa200-worker-clones/remediation",
        "worker_pass_is_proposal": True,
        "proposed_pass_count": 0,
        "input_hashes": INPUT_HASHES,
        "counts": counts,
        "shared_paths_mutated": 0,
        "dedupe": {
            "against_fp211": "no PASS on any fp211 declared or publication identity",
            "against_fresh_lanes": "GHSA-JXX9-PX88-PJ69 routed to fresh-am as AI_NEW_SURFACE_CONTRIBUTOR; no AI_DIRECT_ROOT proposal from this lane",
        },
        "blockers": [
            "No novel first-party GHSA closed all seven gates as AI_INCOMPLETE_REMEDIATION or AI_REINTRODUCTION.",
            "Closest reintroduction (GHSA-P8RR-9CVG-CX5J) fails identity_gate (unreviewed global GHSA, no repo first-party object) and fix_reversal_gate (3.2.8 closer still allows private/loopback).",
            "Closest AI-marked rem series (Scriban 89CF/24C8, GitPython WVPP/2F96) fail uniqueness and/or but_for because they are leftovers of already-counted or preexisting sibling surfaces.",
        ],
        "screened_not_rowed": [
            "fresh-am incomplete-keyword inventory (ImageMagick, goshs, Flowise, ArcadeDB, flask-reuploaded, jackson-core, Gitea GHSA-2R5C / GHSA-7P4H): default REJECT ai_hunk unless an atomic AI rem created a new residual form; not individually cloned",
            "CVE-2026-62181 / GHSA-CV3G-HJ65-PCFH: global advisory not recovered this session; no row invented",
        ],
    }
    (HERE / "result.json").write_text(json.dumps(result, indent=2, ensure_ascii=True) + "\n")
    print(json.dumps(counts, indent=2))


if __name__ == "__main__":
    main()
