#!/usr/bin/env python3
from __future__ import annotations

import datetime
import hashlib
import json
import os
import re
import subprocess
from pathlib import Path

OWNED = Path("/home/hanqing/agents/ai-slop/autoresearch/herdr-260814-w2-s6-grok46-high")
ROOT = Path("/home/hanqing/agents/ai-slop")
SLICE = ROOT / "autoresearch/orchestrator-260814-ghsa200-canvas/wave2/ag-slice-4.jsonl"
SPEC = ROOT / "autoresearch/orchestrator-260814-ghsa200-canvas/wave2/SPEC.md"
CONTRACT = ROOT / "autoresearch/orchestrator-260813-ghsa200-leader/CONTRACT.md"
CLONE_ROOT = Path("/home/hanqing/.cache/ghsa200-worker-clones")
WORK = OWNED / "work"
WORK.mkdir(exist_ok=True)

AI_RE = re.compile(
    r"(copilot|chatgpt|openai|claude|anthropic|cursor|devin|codex|gemini|gpt-4|gpt-5|"
    r"generated by|co-authored-by:\s*(copilot|chatgpt|openai|claude|cursor|codex)|"
    r"made-with:\s*(cursor|copilot|chatgpt)|aider|sweep\.dev|cody|tabnine)",
    re.I,
)
ALL_GATES = [
    "identity_gate",
    "ai_hunk_gate",
    "topology_gate",
    "but_for_gate",
    "fix_reversal_gate",
    "release_gate",
    "uniqueness_gate",
]


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def run(cmd, cwd=None, timeout=30):
    try:
        p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)
        return p.returncode, (p.stdout or "").strip(), (p.stderr or "").strip()
    except Exception as e:
        return 99, "", str(e)


def find_clone(repo: str) -> str | None:
    owner, name = repo.split("/", 1)
    needle = f"{owner}__{name}"
    hits = []
    for dirpath, dirnames, filenames in os.walk(CLONE_ROOT):
        if dirpath.rstrip("/").endswith(needle) and (Path(dirpath) / ".git").exists():
            hits.append(dirpath)
            dirnames[:] = []
    if not hits:
        return None
    hits.sort(key=lambda p: (0 if "commit-gn" in p else 1, p))
    return hits[0]


def find_advisory(ghsa: str) -> dict:
    low = ghsa.lower()
    year_dirs = [
        CLONE_ROOT / "freshness-qa" / "advisory-database",
        CLONE_ROOT / "advisory-database",
        ROOT / ".ai-slop" / "cache",
    ]
    rel = None
    found = None
    for base in year_dirs:
        if not base.exists():
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            for fn in filenames:
                if fn.lower() == f"{low}.json":
                    found = Path(dirpath) / fn
                    break
            if found:
                break
        if found:
            break
    out = {"path": str(found) if found else None, "obj": None}
    if found:
        try:
            out["obj"] = json.loads(found.read_text())
        except Exception:
            out["obj"] = None
    return out


def inspect_sha(clone: str | None, sha: str) -> dict:
    rec = {"sha": sha, "exists": False, "ai": False, "author": None, "subject": None, "body": None, "parents": [], "files": []}
    if not clone:
        return rec
    code, out, _ = run(["git", "cat-file", "-t", sha], cwd=clone)
    if code != 0 or out.strip() != "commit":
        return rec
    rec["exists"] = True
    _, body, _ = run(["git", "show", "-s", "--format=%an <%ae>%n%cn <%ce>%n%P%n%s%n%b", sha], cwd=clone)
    lines = body.splitlines()
    rec["author"] = lines[0] if lines else None
    rec["parents"] = (lines[2].split() if len(lines) > 2 else [])
    rec["subject"] = lines[3] if len(lines) > 3 else None
    rec["body"] = "\n".join(lines[4:]) if len(lines) > 4 else ""
    blob = "\n".join(lines)
    rec["ai"] = bool(AI_RE.search(blob))
    _, files, _ = run(["git", "diff-tree", "--no-commit-id", "--name-only", "-r", sha], cwd=clone)
    rec["files"] = [f for f in files.splitlines() if f][:40]
    return rec


def try_fetch(clone: str, sha: str, repo: str) -> dict:
    rec = inspect_sha(clone, sha)
    if rec["exists"]:
        return rec
    url = f"https://github.com/{repo}.git"
    dest = WORK / "fetches" / repo.replace("/", "__")
    dest.mkdir(parents=True, exist_ok=True)
    gitdir = dest / ".git"
    if not gitdir.exists():
        run(["git", "init", "--bare", str(dest)])
        # blobless single-commit fetch into owned work dir
        code, out, err = run(
            ["git", "fetch", "--filter=blob:none", "--depth=1", url, sha],
            cwd=str(dest),
            timeout=45,
        )
        rec["fetch"] = {"code": code, "out": (out or "")[:400], "err": (err or "")[:400], "url": url, "dest": str(dest)}
        rec2 = inspect_sha(str(dest), sha)
        rec2["fetch"] = rec["fetch"]
        rec2["clone"] = str(dest)
        return rec2
    rec2 = inspect_sha(str(dest), sha)
    if rec2["exists"]:
        rec2["clone"] = str(dest)
        return rec2
    code, out, err = run(
        ["git", "fetch", "--filter=blob:none", "--depth=1", url, sha],
        cwd=str(dest),
        timeout=45,
    )
    rec2 = inspect_sha(str(dest), sha)
    rec2["fetch"] = {"code": code, "out": (out or "")[:400], "err": (err or "")[:400], "url": url, "dest": str(dest)}
    rec2["clone"] = str(dest)
    return rec2


def aliases_from(obj):
    if not obj:
        return []
    aliases = []
    for a in obj.get("aliases") or []:
        aliases.append(a)
    ident = obj.get("identifiers") or []
    for it in ident:
        if isinstance(it, dict) and it.get("value"):
            aliases.append(it["value"])
        elif isinstance(it, str):
            aliases.append(it)
    out = []
    seen = set()
    for a in aliases:
        u = str(a).upper()
        if u.startswith("GHSA-"):
            continue
        if u not in seen:
            seen.add(u)
            out.append(u)
    return out


def summary_from(obj, fallback=""):
    if not obj:
        return fallback
    return (obj.get("summary") or obj.get("details") or fallback or "")[:240].replace("\n", " ")


rows = [json.loads(l) for l in SLICE.read_text().splitlines() if l.strip()]
now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

inspected = []
for i, row in enumerate(rows, 1):
    repo = row["repository"]
    ghsa = row["ghsa_id"]
    clone = find_clone(repo)
    adv = find_advisory(ghsa)
    cand = row["commit_refs"][0]
    rec = inspect_sha(clone, cand)
    if not rec["exists"] and clone:
        rec = try_fetch(clone, cand, repo)
    elif not rec["exists"]:
        rec = try_fetch(None and "", cand, repo) if False else rec
        # still try owned work fetch even without clone
        url_rec = try_fetch(clone or str(WORK / "fetches" / repo.replace("/", "__")), cand, repo)
        rec = url_rec
    extra = []
    for sha in row["commit_refs"][1:]:
        extra.append(inspect_sha(clone, sha))
    inspected.append(
        {
            "row": row,
            "clone": clone,
            "adv": {"path": adv["path"], "aliases": aliases_from(adv["obj"]), "summary": summary_from(adv["obj"], ""), "withdrawn": (adv["obj"] or {}).get("withdrawn") if adv["obj"] else None},
            "cand": rec,
            "extra": extra,
        }
    )

(WORK / "inspect.json").write_text(json.dumps(inspected, indent=2)[:200000])
print("INSPECTED", len(inspected))
for rec in inspected:
    c = rec["cand"]
    print(rec["row"]["ghsa_id"], "clone", bool(rec["clone"]), "exists", c.get("exists"), "ai", c.get("ai"), "adv", bool(rec["adv"]["path"]), "subj", (c.get("subject") or "")[:80])
