#!/usr/bin/env python3
import json, os, subprocess, hashlib
from pathlib import Path

SLICE = Path("/home/hanqing/agents/ai-slop/autoresearch/orchestrator-260814-ghsa200-canvas/sweep/dr-slice-5.jsonl")
ADV_ROOT = Path("/home/hanqing/.cache/ghsa200-worker-clones/commit-af/advisory-database/advisories/github-reviewed")
POOL = Path("/home/hanqing/.cache/ghsa200-sweep-fetch")
OUT = Path("/home/hanqing/agents/ai-slop/autoresearch/herdr-260814-scale5-grok46-high/_evidence.json")

rows = [json.loads(l) for l in SLICE.read_text().splitlines() if l.strip()]

def git(cwd, args, extra_env=None):
    env = os.environ.copy()
    env["GIT_NO_LAZY_FETCH"] = "1"
    if extra_env:
        env.update(extra_env)
    r = subprocess.run(["git", "-C", str(cwd), *args], capture_output=True, text=True, env=env)
    return r.returncode, r.stdout, r.stderr

def find_adv(case_id, published):
    cid = case_id.lower()
    year = published[:4]
    month = published[5:7]
    p = ADV_ROOT / year / month / cid / f"{cid}.json"
    if p.exists():
        return str(p)
    for y in sorted(ADV_ROOT.iterdir()):
        if not y.is_dir():
            continue
        for m in y.iterdir():
            cand = m / cid / f"{cid}.json"
            if cand.exists():
                return str(cand)
    return None

out = []
for row in rows:
    rec = dict(row)
    rec["advisory_json"] = find_adv(row["case_id"], row["published"])
    rec["advisory"] = None
    if rec["advisory_json"]:
        data = json.loads(Path(rec["advisory_json"]).read_text())
        rec["advisory"] = {
            "summary": (data.get("summary") or "")[:400],
            "details": (data.get("details") or "")[:1200],
            "severity": data.get("severity"),
            "withdrawn": data.get("withdrawn_at"),
            "aliases": data.get("aliases") or [],
            "affected": [
                {
                    "package": (a.get("package") or {}).get("name"),
                    "ecosystem": (a.get("package") or {}).get("ecosystem"),
                    "ranges": a.get("ranges"),
                    "versions": a.get("versions"),
                }
                for a in (data.get("affected") or [])[:4]
            ],
            "refs": [r.get("url") for r in (data.get("references") or [])[:12]],
        }
    owner, repo = row["repository"].split("/", 1)
    pool = POOL / f"{owner}__{repo}"
    rec["commit_pool"] = str(pool)
    rec["pool_exists"] = pool.exists()
    rec["ancestor_cat"] = None
    rec["fix_cat"] = None
    rec["ancestor_files"] = []
    rec["fix_files"] = []
    rec["ancestor_stat"] = None
    rec["fix_stat"] = None
    rec["ancestor_msg"] = None
    rec["fix_msg"] = None
    rec["ancestor_show_err"] = None
    rec["fix_show_err"] = None
    rec["is_ancestor"] = None
    rec["ai_marker"] = None
    if pool.exists():
        code, outp, err = git(pool, ["cat-file", "-t", row["ai_ancestor"]])
        rec["ancestor_cat"] = outp.strip() if code == 0 else f"ERR {err.strip()[:200]}"
        code, outp, err = git(pool, ["cat-file", "-t", row["fix_ref"]])
        rec["fix_cat"] = outp.strip() if code == 0 else f"ERR {err.strip()[:200]}"
        code, outp, err = git(pool, ["log", "-1", "--format=%s%n%n%b", row["ai_ancestor"]])
        rec["ancestor_msg"] = (outp if code == 0 else err)[:2500]
        code, outp, err = git(pool, ["log", "-1", "--format=%s%n%n%b", row["fix_ref"]])
        rec["fix_msg"] = (outp if code == 0 else err)[:2500]
        code, outp, err = git(pool, ["diff-tree", "--no-commit-id", "--name-only", "-r", row["ai_ancestor"]])
        rec["ancestor_files"] = [x for x in outp.splitlines() if x][:80]
        rec["ancestor_show_err"] = err[:400] if code != 0 else None
        code, outp, err = git(pool, ["diff-tree", "--no-commit-id", "--name-only", "-r", row["fix_ref"]])
        rec["fix_files"] = [x for x in outp.splitlines() if x][:80]
        rec["fix_show_err"] = err[:400] if code != 0 else None
        code, outp, err = git(pool, ["diff-tree", "--stat", "-r", "--find-renames", row["ai_ancestor"]])
        rec["ancestor_stat"] = (outp if code == 0 else err)[:2500]
        code, outp, err = git(pool, ["diff-tree", "--stat", "-r", "--find-renames", row["fix_ref"]])
        rec["fix_stat"] = (outp if code == 0 else err)[:2500]
        code, outp, err = git(pool, ["merge-base", "--is-ancestor", row["ai_ancestor"], row["fix_ref"]])
        rec["is_ancestor"] = (code == 0)
        msg = rec["ancestor_msg"] or ""
        markers = []
        for needle in ["Co-authored-by: Copilot", "Co-Authored-By: Claude", "Generated by", "Cursor", "GPT", "ChatGPT", "Claude", "Copilot", "codex", "OpenAI"]:
            if needle.lower() in msg.lower():
                markers.append(needle)
        rec["ai_marker"] = markers
    out.append(rec)

OUT.write_text(json.dumps(out, indent=2))
print("wrote", OUT, "rows", len(out))
