import json
from pathlib import Path
p = Path("/home/hanqing/agents/ai-slop/autoresearch/herdr-260814-scale5-grok46-high/_evidence.json")
print("exists", p.exists(), "size", p.stat().st_size if p.exists() else 0)
rows = json.loads(p.read_text())
print("n", len(rows))
for r in rows:
    print("---")
    print(r.get("case_id"), r.get("repository"))
    print("adv", r.get("advisory_json"))
    print("summary", (r.get("advisory_summary") or "")[:300])
    print("withdrawn", r.get("advisory_withdrawn"), "sev", r.get("advisory_severity"))
    print("files", r.get("advisory_files"))
    print("anc_ok", r.get("ancestor_ok"), "fix_ok", r.get("fix_ok"), "anc_of_fix", r.get("ancestor_of_fix"))
    print("marker", r.get("ai_marker"))
    print("anc_subj", r.get("ancestor_subject"))
    print("anc_files", r.get("ancestor_files")[:20] if r.get("ancestor_files") else None)
    print("fix_files", r.get("fix_files")[:20] if r.get("fix_files") else None)
    print("overlap", r.get("overlap_files"))
    print("anc_stat", r.get("ancestor_stat"))
    print("fix_stat", r.get("fix_stat"))
    print("anc_diff_err", r.get("ancestor_diff_err"))
    print("fix_diff_err", r.get("fix_diff_err"))
    print("anc_diff_head", (r.get("ancestor_diff") or "")[:1500])
    print("fix_diff_head", (r.get("fix_diff") or "")[:1500])
