#!/usr/bin/env python3
"""Snapshot current Coolify research and build a conservative exclusion manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


SHA_RE = re.compile(r"(?<![0-9a-f])[0-9a-f]{40}(?![0-9a-f])", re.I)
PUBLIC_ID_RE = re.compile(r"\b(?:CVE-\d{4}-\d{4,}|GHSA-[23456789CFGHJMPQRVWX]{4}(?:-[23456789CFGHJMPQRVWX]{4}){2})\b", re.I)
FINAL_STATUSES = {"CONFIRMED_TRUE_POSITIVE", "PATCH_EQUIVALENT_ALIAS", "REJECTED_NONCAUSAL"}

# Closures newer than the v41 Coolify ledger. These are copied from the current
# claim-grade reports so a mere mention elsewhere does not become an exclusion.
CURRENT_COOLIFY_CLOSURES = [
    ("CVE-2026-34599", "bbb2aa9ad4e0c14517d32272b5e6d83318fde493", "f267a28cb2badc7e712c4592af4d79d090fe5063"),
    ("CVE-2026-34049", "473c32270d72252ee6753afc35c3ea4360d169e0", "b1de75a7c67ce6aee977bd788b41e61837dbe0b9"),
    ("CVE-2026-42148", "18f30b7fabc54938a031867ad34c39a1e9c7c0d7", "dc9322b11f5f4ab96e56af0df7d4f877e96e5e4c"),
    ("CVE-2026-34050", "acff543e09ae5c7f8da78e5a092ebb1e57f24dc0", "0fed553207383f384b93cba24d28122065fa67d5"),
    ("CVE-2026-34149", "473c32270d72252ee6753afc35c3ea4360d169e0", "99043600ee881fd8581185e7590604d9882382cd"),
    ("CVE-2026-32718", "62c394d3a1dba6aa6d4ab1456b7a7911f6b72639", "c15bcd56347fc8c535755791e92e4f6c2af17e3a"),
    ("CVE-2026-34198", "e1fe58639756cf7b232458eddd6978e4ed0031f5", "e1d4b4682efc898ba5aa3751b2da2072f89c7e24"),
    ("CVE-2026-42204", "c9922c30c2a6bf922653a5f2d631aab4fea685c4", "817128c5affa02c1a8f0f1f9a8df54b9dd80bcc1"),
    ("CVE-2026-34167", "a94517f452e225046e01c08385d6a7aedf085c7d", "3e0d48faeaab950bfd063dfca908f1d140316ede"),
]


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def stable_read(path: Path) -> tuple[bytes, dict[str, object]]:
    for _ in range(3):
        before = path.stat()
        data = path.read_bytes()
        after = path.stat()
        if (before.st_size, before.st_mtime_ns) == (after.st_size, after.st_mtime_ns):
            return data, {
                "path": str(path),
                "size": len(data),
                "mtime_ns": after.st_mtime_ns,
                "sha256": sha256_bytes(data),
            }
    raise RuntimeError(f"volatile input did not stabilize: {path}")


def discover(root: Path, owned: Path) -> tuple[list[Path], list[str]]:
    files: set[Path] = set()
    generated_exclusions: list[str] = []
    fix_roots = root / "autoresearch/orchestrator-260811-atomic150/global-batch-v9-inputs/coolify/fix-roots.jsonl"
    coolify_ids = {
        advisory["id"].upper()
        for row in map(json.loads, fix_roots.read_text().splitlines())
        for advisory in row["advisories"]
    }
    for base in (root / "docs", root / "autoresearch"):
        for path in base.rglob("*.md"):
            if owned in path.parents:
                continue
            data = path.read_bytes()
            text = data.decode("utf-8", errors="replace").upper()
            if b"coolify" in data.lower() or any(public_id in text for public_id in coolify_ids):
                files.add(path)
    for path in (root / "scripts").glob("cohort_coolify_*"):
        if path.is_file() and path.suffix in {".py", ".json", ".jsonl"}:
            files.add(path)
    for path in (root / "scripts" / "tests").glob("test_cohort_coolify_*.py"):
        files.add(path)
    orchestrator = root / "autoresearch/orchestrator-260811-atomic150"
    for path in orchestrator.rglob("*"):
        if path.is_file() and "/coolify/" in str(path) and any("v9" in part for part in path.parts):
            files.add(path)
    generated_exclusions.extend([
        "scripts/**/__pycache__/** (generated bytecode)",
        "autoresearch/herdr-260812-coolify-tail/** (this run)",
    ])
    return sorted(files), generated_exclusions


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--snapshot-at", required=True)
    args = parser.parse_args()
    root = args.root.resolve()
    output = args.output.resolve()
    owned = (root / "autoresearch/herdr-260812-coolify-tail").resolve()
    if owned not in output.parents:
        raise SystemExit("output must be inside the owned directory")

    discovered, generated_exclusions = discover(root, owned)
    canonical = {
        "latest_ledger": root / ".ai-slop/state/cohort-v1/coolify-causal-adjudication-ledger-20260801-v41/ledger.json",
        "latest_lineage": root / ".ai-slop/state/cohort-v1/coolify-fix-preimage-lineage-20260801-v2/lineage.json",
        "ai_scan_summary": root / ".ai-slop/state/cohort-v1/ai-commit-scan-coolify-20260801-v4/summary.json",
        "ai_scan_commits": root / ".ai-slop/state/cohort-v1/ai-commit-scan-coolify-20260801-v4/commits.jsonl",
        "strict_200_v3": root / "autoresearch/orchestrator-260811-atomic150/strict-200-v3/ledger.jsonl",
    }
    paths = sorted(set(discovered) | set(canonical.values()))
    snapshots: list[dict[str, object]] = []
    texts: dict[Path, str] = {}
    all_full_shas: set[str] = set()
    public_ids: set[str] = set()
    for path in paths:
        data, snapshot = stable_read(path)
        snapshot["path"] = str(path.relative_to(root))
        snapshots.append(snapshot)
        text = data.decode("utf-8", errors="replace")
        texts[path] = text
        all_full_shas.update(match.lower() for match in SHA_RE.findall(text))
        public_ids.update(match.upper() for match in PUBLIC_ID_RE.findall(text))

    ledger = json.loads(texts[canonical["latest_ledger"]])
    final_edges: list[dict[str, object]] = []
    final_shas: set[str] = set()
    mechanisms: set[str] = set()
    routed_edge_count = 0
    for row in ledger["edge_ledger"]:
        candidate = row["candidate_sha"].lower()
        fix = row["fix_sha"].lower()
        if row["status"] not in FINAL_STATUSES:
            routed_edge_count += 1
            continue
        mechanism = row.get("mechanism_group")
        final_edges.append({
            "candidate_sha": candidate,
            "fix_sha": fix,
            "status": row["status"],
            "adjudication": row["adjudication"],
            "mechanism_group": mechanism,
        })
        final_shas.update((candidate, fix))
        if mechanism:
            mechanisms.add(mechanism)

    hard_public_ids: set[str] = set()
    for public_id, candidate, fix in CURRENT_COOLIFY_CLOSURES:
        hard_public_ids.add(public_id)
        final_shas.update((candidate, fix))
        final_edges.append({
            "candidate_sha": candidate,
            "fix_sha": fix,
            "status": "CURRENT_REPORT_CLOSURE",
            "adjudication": public_id,
            "mechanism_group": f"current_report_component:{public_id}",
        })
        mechanisms.add(f"current_report_component:{public_id}")

    final_edges = list({
        (row["candidate_sha"], row["fix_sha"]): row for row in final_edges
    }.values())

    manifest = {
        "schema_version": 1,
        "task": "Coolify-only unexamined tail exclusion manifest",
        "snapshot_at": args.snapshot_at,
        "snapshot_boundary": "Each input is bound by path, size, mtime_ns, and SHA-256; later shared-checkout changes are outside this run.",
        "canonical_artifacts": {key: str(value.relative_to(root)) for key, value in canonical.items()},
        "input_files": snapshots,
        "generated_path_exclusions": generated_exclusions,
        "hard_exclusions": {
            "terminal_edges": sorted(final_edges, key=lambda row: (row["candidate_sha"], row["fix_sha"])),
            "terminal_edge_shas": sorted(final_shas),
            "terminal_mechanism_groups": sorted(mechanisms),
            "adjudicated_public_ids": sorted(hard_public_ids),
        },
        "diagnostic_seen_not_automatically_excluded": {
            "all_full_shas_mentioned": sorted(all_full_shas),
            "public_ids_mentioned_in_current_material": sorted(public_ids),
            "nonterminal_ledger_edge_count": routed_edge_count,
            "rule": "A routed/deferred observation stays eligible for row-level adjudication unless its pair, public identity, or mechanism is already terminal elsewhere.",
        },
        "counts": {
            "input_files": len(snapshots),
            "terminal_edges": len(final_edges),
            "terminal_edge_shas": len(final_shas),
            "terminal_mechanism_groups": len(mechanisms),
            "public_ids_mentioned": len(public_ids),
            "all_full_shas_mentioned": len(all_full_shas),
            "nonterminal_ledger_edges": routed_edge_count,
        },
    }
    assert len(final_edges) == len({(row["candidate_sha"], row["fix_sha"]) for row in final_edges})
    assert all(len(sha) == 40 for sha in all_full_shas | final_shas)
    output.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(manifest["counts"], sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
