#!/usr/bin/env python3
"""Phase 2: enumerate the pagination-complete advisory delta (frozen -> current)
across advisories/unreviewed and advisories/github-reviewed, apply baseline
exclusions and identity-collision routing.

Emits:
  delta-manifest.jsonl   - all changed paths (routing notes)
  reviewed-delta.jsonl   - github-reviewed rows only (731 A / 148 M / 0 D expected)
  delta-summary.json
"""
import hashlib
import json
import re
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from build_delta import (  # noqa: E402
    OWN, SCRATCH, GITDIR, FROZEN_COMMIT, CURRENT_COMMIT, sha256_file, sha256_bytes, git,
)


def cat_file_batch(blob_shas):
    proc = subprocess.Popen(
        ["git", "--git-dir", str(GITDIR), "cat-file", "--batch"],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    out = {}
    for sha in blob_shas:
        proc.stdin.write((sha + "\n").encode())
        proc.stdin.flush()
        header = proc.stdout.readline().decode()
        m = re.match(r"^([0-9a-f]{40}) blob (\d+)", header)
        if not m:
            continue
        size = int(m.group(2))
        data = proc.stdout.read(size)
        proc.stdout.read(1)
        out[sha] = data
    proc.stdin.close()
    proc.wait()
    return out


def summarize(data: dict) -> dict:
    out = {}
    out["aliases"] = [a.upper() for a in data.get("aliases", [])]
    out["published"] = data.get("published")
    out["modified"] = data.get("modified")
    out["summary"] = (data.get("summary") or "")[:240]
    out["github_reviewed"] = data.get("database_specific", {}).get("github_reviewed")
    out["withdrawn"] = data.get("withdrawn")
    affected = data.get("affected", [])
    out["packages"] = [p.get("package", {}).get("name") for p in affected]
    out["ecosystems"] = sorted({p.get("package", {}).get("ecosystem") for p in affected
                                if p.get("package", {}).get("ecosystem")})
    ranges = []
    n_fixed = 0
    for p in affected:
        for r in p.get("ranges", []):
            evs = r.get("events", [])
            introduced = [e.get("introduced") for e in evs if "introduced" in e]
            fixed = [e.get("fixed") for e in evs if "fixed" in e]
            last_affected = [e.get("last_affected") for e in evs if "last_affected" in e]
            n_fixed += len(fixed)
            ranges.append({"type": r.get("type"), "introduced": introduced,
                           "fixed": fixed, "last_affected": last_affected})
    out["ranges"] = ranges
    out["n_fixed_events"] = n_fixed
    refs = data.get("references", []) or []
    out["ref_urls"] = [r.get("url") for r in refs if r.get("url")]
    repos = set()
    for u in out["ref_urls"]:
        m = re.match(r"https?://(?:www\.)?github\.com/([^/\s#?]+)/([^/\s#?]+)", u)
        if m and m.group(1) not in ("advisories", "security-advisories", "ghsecuritylab", "sponsors"):
            repos.add(f"{m.group(1)}/{m.group(2)}")
    out["ref_repos"] = sorted(repos)
    out["ref_commit_shas"] = sorted({u.split("/")[-1] for u in out["ref_urls"]
                                     if "/commit/" in u or "/commits/" in u})
    details = (data.get("details") or "")
    text = (details + " " + (data.get("summary") or "")).lower()
    out["ai_kw_hits"] = [k for k in ("copilot", "claude", "chatgpt", "gpt-", "generated by ai",
                                     "aider", "codex", "openclaw", "cursor ai", "llm",
                                     "github copilot", "codeium", "tabnine", "codewhisperer",
                                     "amazon q", "gemini", "ai-generated", "ai generated")
                         if k in text]
    return out


def diff_paths(dirname: str):
    """Yield (status, path, oldsha, newsha) for the tree diff of one dir."""
    raw = git("diff", "--raw", "--full-index", "-z", FROZEN_COMMIT, CURRENT_COMMIT,
              "--", dirname)
    pending = None
    for chunk in raw.split("\x00"):
        if not chunk.strip():
            continue
        if chunk[0] == ":":
            _, _, oldsha, newsha, status = chunk.split(" ")
            pending = (status, oldsha, newsha)
        else:
            yield (pending[0], chunk, pending[1], pending[2])


def main() -> int:
    items = [(s, p, o, n, "advisories/unreviewed") for s, p, o, n in diff_paths("advisories/unreviewed")]
    items += [(s, p, o, n, "advisories/github-reviewed") for s, p, o, n in diff_paths("advisories/github-reviewed")]

    blobs_needed = {sha for _, _, o, n, _ in items for sha in (o, n) if re.match(r"^[0-9a-f]{40}$", sha)}
    contents = cat_file_batch(sorted(blobs_needed))

    freeze = json.loads((OWN / "exclusion-freeze.json").read_text())
    baseline_ids = {i.upper() for i in freeze["baseline_exclusion"]["declared_public_ids"]}
    sibling_ids = {i.upper(): d for d, v in freeze["sibling_declared"].items() for i in v["ids"]}

    rows = []
    reviewed_rows = []
    seen_alias = {}
    for status, path, oldsha, newsha, dirname in items:
        gid = path.split("/")[-2].upper()
        new_blob = contents.get(newsha, b"")
        old_blob = contents.get(oldsha, b"")
        try:
            new_data = json.loads(new_blob) if new_blob else None
        except Exception:
            new_data = None
        try:
            old_data = json.loads(old_blob) if old_blob else None
        except Exception:
            old_data = None
        ns = summarize(new_data) if new_data is not None else {"aliases": []}
        os_ = summarize(old_data) if old_data is not None else {"aliases": []}
        row = {
            "status": {"A": "ADDED", "M": "MODIFIED", "D": "DELETED"}[status],
            "ghsa": gid,
            "path": path,
            "dirname": dirname,
            "old_blob_sha1": oldsha if oldsha != "0" * 40 else None,
            "new_blob_sha1": newsha if newsha != "0" * 40 else None,
            "blob_sha256": sha256_bytes(new_blob) if new_blob else None,
            "old": os_, "new": ns,
        }
        collision = []
        if gid in baseline_ids:
            collision.append("baseline_ghsa_declared")
        for a in ns["aliases"]:
            if a in baseline_ids:
                collision.append(f"baseline_alias:{a}")
            if a in seen_alias and seen_alias[a] != gid:
                collision.append(f"delta_alias_collision:{seen_alias[a]}")
            elif a not in seen_alias:
                seen_alias[a] = gid
        for sid, d in sibling_ids.items():
            if gid == sid:
                collision.append(f"sibling_declared:{d}")
            for a in ns["aliases"]:
                if a == sid:
                    collision.append(f"sibling_alias:{d}:{a}")
        row["collisions"] = sorted(set(collision))
        row["excluded"] = bool(collision)
        reviewed = dirname == "advisories/github-reviewed"
        if row["status"] == "DELETED":
            row["triage"] = "DELETED_WITHDRAWN_REVIEWED" if reviewed else "DELETED_UNREVIEWED"
        elif row["status"] == "MODIFIED":
            row["triage"] = "MODIFIED_REVIEWED" if reviewed else "MODIFIED_UNREVIEWED"
        else:
            row["triage"] = "ADDED_REVIEWED" if reviewed else "ADDED_UNREVIEWED"
        rows.append(row)
        if reviewed:
            reviewed_rows.append(row)

    manifest_path = OWN / "delta-manifest.jsonl"
    with open(manifest_path, "w") as f:
        for r in rows:
            f.write(json.dumps(r, sort_keys=True) + "\n")
    reviewed_path = OWN / "reviewed-delta.jsonl"
    with open(reviewed_path, "w") as f:
        for r in reviewed_rows:
            f.write(json.dumps(r, sort_keys=True) + "\n")

    triage = Counter(r["triage"] for r in rows)
    summary = {
        "schema_version": 1,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "frozen_commit": FROZEN_COMMIT,
        "current_commit": CURRENT_COMMIT,
        "current_head_date_utc": git("show", "-s", "--format=%cI", CURRENT_COMMIT).strip(),
        "pagination_completeness": {
            "method": "full git clone of official github/advisory-database; tree-to-tree diff is complete by construction",
            "clone_origin": "https://github.com/github/advisory-database.git",
            "clone_alternates_reference": "/home/hanqing/.cache/cve-analyzer/advisory-database (read-only)",
            "frozen_tree": git("rev-parse", f"{FROZEN_COMMIT}^{{tree}}").strip(),
            "current_tree": git("rev-parse", f"{CURRENT_COMMIT}^{{tree}}").strip(),
        },
        "triage_counts": dict(sorted(triage.items())),
        "reviewed_counts": {t: sum(1 for r in reviewed_rows if r["triage"] == t)
                            for t in ("ADDED_REVIEWED", "MODIFIED_REVIEWED", "DELETED_WITHDRAWN_REVIEWED")},
        "excluded_reviewed": sum(1 for r in reviewed_rows if r["excluded"]),
        "total_changed_paths": len(rows),
        "manifest_sha256": sha256_file(manifest_path),
        "reviewed_delta_sha256": sha256_file(reviewed_path),
    }
    (OWN / "delta-summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps({k: v for k, v in summary.items() if k != "pagination_completeness"}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
