#!/usr/bin/env python3
"""Freeze a recall-first causal inventory for NLTK CVE-2026-33236.

The artifact conserves the union of a frozen repository inventory, every
currently reachable local ref, and recovered squash members.  AI attribution
has three additive tiers: Source-v3 explicit evidence, the frozen observation
policy, and a deliberately broad metadata-regex candidate lane.  None of
those lanes, semantic ranking, ancestry, or a later model verdict may delete a
commit from the finite inventory.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import tempfile
from collections import Counter
from collections.abc import Mapping
from pathlib import Path

from cve_analyzer.provenance import scan_repo_ai_commit_index


FULL_SHA = re.compile(r"[0-9a-f]{40}")
REPOSITORY_IDENTITY = "github.com/nltk/nltk"
ADVISORY = "CVE-2026-33236"
FROZEN_COMMIT_COUNT = 15_430
AFFECTED_SHA = "bbaae83db86a0f49e00f5b0db44a7254c268de9b"
FIX_MEMBER_SHA = "75917efc66ab122bf4b7ea9ffc33e8f8b39c5dce"
FIX_MERGE_SHA = "89fe2ec2c6bae6e2e7a46dad65cc34231976ed8a"
EARLIEST_PIPELINE_SHA = "fa242f5e10511cb2400396ebb56964becef12799"

CODE_PATHS: tuple[str, ...] = (
    "nltk/downloader.py",
    "nltk/pathsec.py",
)
CONTEXT_PATHS: tuple[str, ...] = (
    "nltk/test/unit/test_downloader.py",
    "nltk/test/unit/test_downloader_unzip.py",
)
RISK_PATHS = CODE_PATHS + CONTEXT_PATHS

# POSIX ERE consumed by Git.  This intentionally over-approximates the source,
# propagation, sink, and guard vocabulary.  It is a ranking signal only.
GIT_SEMANTIC_ERE = (
    r"subdir|info\.id|info\.filename|self\.filename|Package\.fromxml|"
    r"__dict__\.update|ElementTree\.parse|urlopen|os\.path\.join|"
    r"open\(|pathsec\.open|realpath|abspath|commonpath|isabs|normpath|"
    r"Path traversal|outside download|\.\."
)

SIGNAL_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "xml_attribute_source",
        re.compile(
            r"\bsubdir\b|\binfo\.id\b|\bself\.id\b|Package\.fromxml|"
            r"__dict__\.update"
        ),
    ),
    (
        "remote_index_source",
        re.compile(r"ElementTree\.parse|\burlopen\b|\bself\._url\b"),
    ),
    (
        "path_composition",
        re.compile(
            r"os\.path\.join|\binfo\.filename\b|\bself\.filename\b|"
            r"\bfilepath\b"
        ),
    ),
    (
        "filesystem_write_sink",
        re.compile(r"\bopen\(|\bpathsec\.open\(|\.extract\("),
    ),
    (
        "path_containment_guard",
        re.compile(
            r"realpath|abspath|commonpath|isabs|normpath|Path traversal|"
            r"outside download|\.\."
        ),
    ),
)

# Candidate-only metadata signals.  These are broader than Source-v3 on
# purpose.  They may produce false positives, but cannot support a publication
# attribution claim without stronger evidence.
WEAK_AI_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "tool_name_token",
        re.compile(
            r"\b(?:copilot|claude|chatgpt|openai|codex|gemini|cursor|aider|"
            r"devin|sweep|qwen|deepseek|grok|opencode|codeium|windsurf|"
            r"tabnine|cody|sourcegraph)\b|mistral[ -]?vibe",
            re.IGNORECASE,
        ),
    ),
    (
        "generic_ai_authorship_phrase",
        re.compile(
            r"\bAI[- ]assisted\b|\bgenerated by AI\b|"
            r"\blarge language model\b|\bLLM[- ](?:generated|assisted)\b",
            re.IGNORECASE,
        ),
    ),
    (
        "agent_log_url",
        re.compile(r"Agent-Logs-Url\s*:", re.IGNORECASE),
    ),
)

KNOWN_STRICT_AI_AFFECTED_CODE_ANCESTORS = frozenset(
    {
        "1f8eb13f385f0c49a32241d8dedc2c45b2cc22b6",
        "3bc1214f7db0bc0d261196fac42c4dca74ce6d63",
        "5fbbeb47edb1f93c022693765b4db018a514ff84",
        "cc4bec20672ae0e67d21db47a4bbe8418d239671",
    }
)
KNOWN_WEAK_ONLY_AFFECTED_CODE_ANCESTORS = frozenset(
    {
        "394eef88b0d5fd2d8571622f43cf7c3205b59355",
        "90712b608d9a8a8711016376223f9ba20bf5634d",
        "c88d8469d46b8743638dce75d07f67878bada9d1",
    }
)

ORIGIN_REQUIRED_SNIPPETS: tuple[str, ...] = (
    "self.filename = os.path.join(subdir, id+ext)",
    "self.__dict__.update(kw)",
    "filepath = os.path.join(download_dir, info.filename)",
    "outfile = open(filepath, 'wb')",
)
FIX_REQUIRED_SNIPPETS: tuple[str, ...] = (
    "os.path.isabs(subdir)",
    '".." in subdir.replace("\\\\", "/").split("/")',
    "real_download = os.path.realpath(os.path.abspath(download_dir))",
    "real_filepath = os.path.realpath(os.path.abspath(filepath))",
    "real_filepath.startswith(real_download + os.sep)",
)


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", type=Path, required=True)
    parser.add_argument("--commit-universe", type=Path, required=True)
    parser.add_argument("--squash-candidates", type=Path, required=True)
    parser.add_argument("--squash-relations", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args(argv)


def _git(repository: Path, arguments: list[str], *, timeout: int = 300) -> str:
    try:
        completed = subprocess.run(
            ["git", "-C", str(repository), *arguments],
            capture_output=True,
            check=False,
            env={**os.environ, "GIT_NO_LAZY_FETCH": "1"},
            timeout=timeout,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise ValueError(f"git {' '.join(arguments)} failed: {exc}") from exc
    if completed.returncode != 0:
        detail = completed.stderr.decode("utf-8", errors="replace")[:500]
        raise ValueError(f"git {' '.join(arguments)} failed: {detail}")
    return completed.stdout.decode("utf-8", errors="strict")


def _load_jsonl(path: Path) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    try:
        with path.open(encoding="utf-8") as handle:
            for line_number, line in enumerate(handle, start=1):
                if not line.strip():
                    continue
                value = json.loads(line)
                if not isinstance(value, dict):
                    raise ValueError(f"{path}:{line_number}: row is not an object")
                rows.append(value)
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read JSONL {path}: {exc}") from exc
    return rows


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _sha_inventory_digest(shas: set[str]) -> str:
    return _sha256_bytes("".join(f"{sha}\n" for sha in sorted(shas)).encode())


def _atomic_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        raise ValueError(f"output already exists: {path}")
    encoded = (
        json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    ).encode()
    with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
        handle.write(encoded)
        temporary = Path(handle.name)
    os.replace(temporary, path)


def _validated_shas(values: set[str], *, label: str) -> set[str]:
    if not all(FULL_SHA.fullmatch(value) for value in values):
        raise ValueError(f"{label} contains a malformed commit identity")
    return values


def _all_reachable_commits(repository: Path) -> set[str]:
    return _validated_shas(
        set(_git(repository, ["rev-list", "--all"]).split()),
        label="all-ref inventory",
    )


def _path_history(repository: Path) -> set[str]:
    return _validated_shas(
        set(
            _git(
                repository,
                ["log", "--all", "--format=%H", "--", *RISK_PATHS],
            ).split()
        ),
        label="risk-path history",
    )


def _semantic_history(repository: Path) -> set[str]:
    return _validated_shas(
        set(
            _git(
                repository,
                [
                    "log",
                    "--all",
                    "--format=%H",
                    "-G",
                    GIT_SEMANTIC_ERE,
                    "--",
                    *CODE_PATHS,
                ],
            ).split()
        ),
        label="semantic history",
    )


def _commit_metadata(repository: Path, sha: str) -> dict[str, object]:
    value = _git(
        repository,
        ["show", "-s", "--format=%H%x00%P%x00%an%x00%ae%x00%aI%x00%B", sha],
    )
    fields = value.split("\x00", 5)
    if len(fields) != 6 or fields[0] != sha:
        raise ValueError(f"unexpected commit metadata for {sha}")
    message = fields[5].rstrip("\n")
    changed_files = sorted(
        {
            line
            for line in _git(
                repository,
                [
                    "diff-tree",
                    "--root",
                    "--no-commit-id",
                    "--name-only",
                    "-r",
                    sha,
                ],
            ).splitlines()
            if line
        }
    )
    return {
        "sha": sha,
        "parents": fields[1].split(),
        "author_name": fields[2],
        "author_email": fields[3],
        "authored_at": fields[4],
        "subject": message.splitlines()[0] if message else "",
        "message": message,
        "changed_files": changed_files,
    }


def _all_ref_message_metadata(repository: Path) -> dict[str, dict[str, str]]:
    output = _git(
        repository,
        ["log", "--all", "--format=%H%x00%an%x00%ae%x00%B%x1e"],
    )
    rows: dict[str, dict[str, str]] = {}
    for raw_record in output.split("\x1e"):
        record = raw_record.strip("\n")
        if not record:
            continue
        fields = record.split("\x00", 3)
        if len(fields) != 4 or not FULL_SHA.fullmatch(fields[0]):
            raise ValueError("all-ref metadata stream is malformed")
        rows[fields[0]] = {
            "author_name": fields[1],
            "author_email": fields[2],
            "message": fields[3].rstrip("\n"),
        }
    return rows


def _weak_metadata_matches(metadata: Mapping[str, object]) -> list[dict[str, str]]:
    haystack = "\n".join(
        str(metadata.get(field, ""))
        for field in ("author_name", "author_email", "message")
    )
    matches: list[dict[str, str]] = []
    for name, pattern in WEAK_AI_PATTERNS:
        match = pattern.search(haystack)
        if match:
            matches.append(
                {
                    "candidate_signal": name,
                    "matched_text": match.group(0)[:200],
                }
            )
    return matches


def _signal_changes(repository: Path, sha: str) -> list[dict[str, object]]:
    diff = _git(
        repository,
        [
            "show",
            "--format=",
            "--no-ext-diff",
            "--no-renames",
            "--unified=0",
            sha,
            "--",
            *CODE_PATHS,
        ],
    )
    changes: list[dict[str, object]] = []
    current_path = ""
    for line in diff.splitlines():
        if line.startswith("diff --git a/"):
            fields = line.split(" ", 3)
            if len(fields) >= 4 and fields[3].startswith("b/"):
                current_path = fields[3][2:]
            continue
        if line.startswith("+++ b/"):
            current_path = line[6:]
            continue
        if line.startswith("--- a/"):
            current_path = line[6:]
            continue
        if not line.startswith(("+", "-")) or line.startswith(("+++", "---")):
            continue
        categories = [
            name for name, pattern in SIGNAL_PATTERNS if pattern.search(line[1:])
        ]
        if categories:
            changes.append(
                {
                    "sign": "added" if line.startswith("+") else "removed",
                    "path": current_path,
                    "categories": categories,
                    "line": line[1:500],
                }
            )
    return changes


def _is_ancestor(repository: Path, ancestor: str, descendant: str) -> bool:
    completed = subprocess.run(
        [
            "git",
            "-C",
            str(repository),
            "merge-base",
            "--is-ancestor",
            ancestor,
            descendant,
        ],
        capture_output=True,
        check=False,
        env={**os.environ, "GIT_NO_LAZY_FETCH": "1"},
        timeout=60,
    )
    if completed.returncode not in {0, 1}:
        raise ValueError(f"cannot test ancestry {ancestor} -> {descendant}")
    return completed.returncode == 0


def _object_exists(repository: Path, sha: str) -> bool:
    completed = subprocess.run(
        ["git", "-C", str(repository), "cat-file", "-e", f"{sha}^{{commit}}"],
        capture_output=True,
        check=False,
        env={**os.environ, "GIT_NO_LAZY_FETCH": "1"},
        timeout=60,
    )
    return completed.returncode == 0


def _file_exists(repository: Path, revision: str, path: str) -> bool:
    completed = subprocess.run(
        ["git", "-C", str(repository), "cat-file", "-e", f"{revision}:{path}"],
        capture_output=True,
        check=False,
        env={**os.environ, "GIT_NO_LAZY_FETCH": "1"},
        timeout=60,
    )
    return completed.returncode == 0


def _file_at(repository: Path, revision: str, path: str) -> str:
    return _git(repository, ["show", f"{revision}:{path}"])


def _priority(
    *,
    ancestor_of_affected: bool,
    code_path_hit: bool,
    context_path_hit: bool,
    semantic_hit: bool,
) -> str:
    if ancestor_of_affected and code_path_hit and semantic_hit:
        return "P0_AI_CAUSAL_SEMANTIC_CODE"
    if ancestor_of_affected and code_path_hit:
        return "P1_AI_AFFECTED_CODE_HISTORY"
    if ancestor_of_affected and context_path_hit:
        return "P2_AI_AFFECTED_CONTEXT_HISTORY"
    if ancestor_of_affected:
        return "P3_AI_ANCESTRY_FALLBACK"
    return "P4_NON_ANCESTOR_RETAINED"


def _exact_transitions(
    repository: Path,
    *,
    source_v3_shas: set[str],
    frozen_ai_shas: set[str],
    weak_ai_shas: set[str],
) -> list[dict[str, object]]:
    origin_parents = _git(
        repository, ["show", "-s", "--format=%P", EARLIEST_PIPELINE_SHA]
    ).split()
    if len(origin_parents) != 1:
        raise ValueError("earliest pipeline transition must have one parent")
    origin_after = _file_at(repository, EARLIEST_PIPELINE_SHA, CODE_PATHS[0])
    origin_checks = {
        "parent_lacks_downloader_file": not _file_exists(
            repository, origin_parents[0], CODE_PATHS[0]
        ),
        "child_contains_complete_source_path_sink_chain": all(
            snippet in origin_after for snippet in ORIGIN_REQUIRED_SNIPPETS
        ),
    }
    if not all(origin_checks.values()):
        raise ValueError(f"earliest pipeline transition changed: {origin_checks}")

    fix_parents = _git(
        repository, ["show", "-s", "--format=%P", FIX_MEMBER_SHA]
    ).split()
    if fix_parents != [AFFECTED_SHA]:
        raise ValueError("fix-member parent changed")
    fix_before = _file_at(repository, AFFECTED_SHA, CODE_PATHS[0])
    fix_after = _file_at(repository, FIX_MEMBER_SHA, CODE_PATHS[0])
    fix_checks = {
        "before_lacks_new_guard_snippets": all(
            snippet not in fix_before for snippet in FIX_REQUIRED_SNIPPETS
        ),
        "after_contains_new_guard_snippets": all(
            snippet in fix_after for snippet in FIX_REQUIRED_SNIPPETS
        ),
    }
    if not all(fix_checks.values()):
        raise ValueError(f"fix transition changed: {fix_checks}")

    def attribution(sha: str) -> dict[str, bool]:
        return {
            "source_v3_explicit": sha in source_v3_shas,
            "frozen_observed_ai": sha in frozen_ai_shas,
            "broad_metadata_candidate": sha in weak_ai_shas,
        }

    return [
        {
            "sha": EARLIEST_PIPELINE_SHA,
            "parent": origin_parents[0],
            "kind": "EARLIEST_COMPLETE_XML_TO_ARBITRARY_FILE_WRITE_PIPELINE",
            "checks": origin_checks,
            "ai_evidence": attribution(EARLIEST_PIPELINE_SHA),
            "claim": (
                "The parent has no nltk/downloader.py; the child introduces XML "
                "attribute loading, attacker-controlled filename composition, and "
                "the direct file-write sink in one commit."
            ),
        },
        {
            "sha": FIX_MEMBER_SHA,
            "parent": AFFECTED_SHA,
            "kind": "XML_COMPONENT_VALIDATION_AND_WRITE_CONTAINMENT_FIX",
            "checks": fix_checks,
            "ai_evidence": attribution(FIX_MEMBER_SHA),
            "claim": (
                "The fix validates XML subdir/id components and adds a real-path "
                "containment check before the existing write."
            ),
        },
    ]


def _build_inventory(
    repository: Path,
    universe_rows: list[dict[str, object]],
    squash_candidate_rows: list[dict[str, object]],
    relation_rows: list[dict[str, object]],
    *,
    input_digests: Mapping[str, str],
) -> dict[str, object]:
    repository_rows = [
        row
        for row in universe_rows
        if row.get("repository_identity") == REPOSITORY_IDENTITY
    ]
    universe_shas = _validated_shas(
        {str(row.get("sha", "")) for row in repository_rows},
        label="frozen commit universe",
    )
    if len(universe_shas) != FROZEN_COMMIT_COUNT:
        raise ValueError("frozen NLTK commit-universe count changed")

    closure_shas = _validated_shas(
        {str(row.get("sha", "")) for row in squash_candidate_rows},
        label="squash candidate closure",
    )
    member_shas = _validated_shas(
        {str(row.get("origin_sha", "")) for row in relation_rows},
        label="squash-member closure",
    )
    carrier_shas = _validated_shas(
        {str(row.get("landed_sha", "")) for row in relation_rows},
        label="squash-carrier closure",
    )

    all_ref_shas = _all_reachable_commits(repository)
    path_shas = _path_history(repository)
    semantic_shas = _semantic_history(repository)
    if not semantic_shas <= path_shas <= all_ref_shas:
        raise ValueError("live semantic/path history escaped all refs")

    scan = scan_repo_ai_commit_index(repository, REPOSITORY_IDENTITY)
    if scan.get("complete") is not True:
        raise ValueError(f"Source-v3 scan is incomplete: {scan.get('error')}")
    scan_rows = scan.get("commits")
    if not isinstance(scan_rows, list):
        raise ValueError("Source-v3 rows are malformed")
    source_by_sha = {
        str(row["sha"]): row for row in scan_rows if isinstance(row, Mapping)
    }
    source_v3_shas = _validated_shas(set(source_by_sha), label="Source-v3 inventory")
    if not source_v3_shas <= all_ref_shas:
        raise ValueError("Source-v3 candidates escaped current refs")

    frozen_by_sha = {
        str(row["sha"]): row
        for row in repository_rows
        if row.get("observed_ai_unit") is True
    }
    frozen_ai_shas = set(frozen_by_sha)

    retained_shas = (
        universe_shas
        | all_ref_shas
        | closure_shas
        | member_shas
        | carrier_shas
        | source_v3_shas
        | frozen_ai_shas
    )
    missing_objects = sorted(
        sha
        for sha in retained_shas - all_ref_shas
        if not _object_exists(repository, sha)
    )
    if missing_objects:
        raise ValueError(
            f"retained commit objects are unavailable: {missing_objects[:3]}"
        )

    # Ref churn can hide relevant paths from `git log --all`; inspect every
    # retained-but-unreachable identity directly and add it back to the lanes.
    direct_scan_shas = retained_shas - all_ref_shas
    direct_metadata: dict[str, dict[str, object]] = {}
    for sha in sorted(direct_scan_shas):
        metadata = _commit_metadata(repository, sha)
        direct_metadata[sha] = metadata
        changed_files = set(str(path) for path in metadata["changed_files"])
        if changed_files & set(RISK_PATHS):
            path_shas.add(sha)
        if changed_files & set(CODE_PATHS) and _signal_changes(repository, sha):
            semantic_shas.add(sha)

    # Broad metadata matching is evaluated over the entire retained universe,
    # not merely current refs or affected files.  This is intentionally noisy.
    message_metadata: dict[str, Mapping[str, object]] = _all_ref_message_metadata(
        repository
    )
    message_metadata.update(direct_metadata)
    if set(message_metadata) != retained_shas:
        missing = retained_shas - set(message_metadata)
        extra = set(message_metadata) - retained_shas
        raise ValueError(
            f"metadata inventory mismatch: missing={len(missing)} extra={len(extra)}"
        )
    weak_matches_by_sha = {
        sha: matches
        for sha in sorted(retained_shas)
        if (matches := _weak_metadata_matches(message_metadata[sha]))
    }
    weak_ai_shas = set(weak_matches_by_sha)

    attribution_candidate_shas = source_v3_shas | frozen_ai_shas | weak_ai_shas
    metadata_cache: dict[str, dict[str, object]] = dict(direct_metadata)

    def metadata_for(sha: str) -> dict[str, object]:
        if sha not in metadata_cache:
            metadata_cache[sha] = _commit_metadata(repository, sha)
        return metadata_cache[sha]

    semantic_rows: list[dict[str, object]] = []
    semantic_counts: Counter[str] = Counter()
    for sha in sorted(semantic_shas):
        changes = _signal_changes(repository, sha)
        semantic_counts.update(
            category for change in changes for category in change.get("categories", [])
        )
        semantic_rows.append(
            {
                **metadata_for(sha),
                "signal_changes": changes,
                "source_v3_explicit": sha in source_v3_shas,
                "frozen_observed_ai": sha in frozen_ai_shas,
                "broad_metadata_candidate": sha in weak_ai_shas,
                "squash_member": sha in member_shas,
                "squash_carrier": sha in carrier_shas,
            }
        )

    candidate_rows: list[dict[str, object]] = []
    priority_counts: Counter[str] = Counter()
    for sha in sorted(attribution_candidate_shas):
        metadata = metadata_for(sha)
        changed_files = set(str(path) for path in metadata["changed_files"])
        code_path_hits = sorted(changed_files & set(CODE_PATHS))
        context_path_hits = sorted(changed_files & set(CONTEXT_PATHS))
        ancestor_of_affected = _is_ancestor(repository, sha, AFFECTED_SHA)
        priority = _priority(
            ancestor_of_affected=ancestor_of_affected,
            code_path_hit=bool(code_path_hits),
            context_path_hit=bool(context_path_hits),
            semantic_hit=sha in semantic_shas,
        )
        priority_counts[priority] += 1
        evidence_contracts = []
        if sha in source_v3_shas:
            evidence_contracts.append("SOURCE_V3_EXPLICIT_ATTRIBUTION")
        if sha in frozen_ai_shas:
            evidence_contracts.append("FROZEN_OBSERVED_AI_UNIT")
        if sha in weak_ai_shas:
            evidence_contracts.append("BROAD_METADATA_REGEX_CANDIDATE_ONLY")
        candidate_rows.append(
            {
                **metadata,
                "evidence_contracts": sorted(evidence_contracts),
                "source_matches": source_by_sha.get(sha, {}).get("source_matches", []),
                "frozen_ai_routes": frozen_by_sha.get(sha, {}).get("ai_routes", []),
                "frozen_ai_tools": frozen_by_sha.get(sha, {}).get("ai_tools", []),
                "broad_metadata_matches": weak_matches_by_sha.get(sha, []),
                "code_path_hits": code_path_hits,
                "context_path_hits": context_path_hits,
                "semantic_signal_hit": sha in semantic_shas,
                "ancestor_of_affected_state": ancestor_of_affected,
                "ancestor_of_fix_member": _is_ancestor(repository, sha, FIX_MEMBER_SHA),
                "ancestor_of_public_fix_merge": _is_ancestor(
                    repository, sha, FIX_MERGE_SHA
                ),
                "is_fix_member": sha == FIX_MEMBER_SHA,
                "is_public_fix_merge": sha == FIX_MERGE_SHA,
                "squash_member": sha in member_shas,
                "squash_carrier": sha in carrier_shas,
                "priority": priority,
                "retained": True,
            }
        )

    strict_affected_code = {
        str(row["sha"])
        for row in candidate_rows
        if "SOURCE_V3_EXPLICIT_ATTRIBUTION" in row["evidence_contracts"]
        and row["ancestor_of_affected_state"] is True
        and row["code_path_hits"]
    }
    if not KNOWN_STRICT_AI_AFFECTED_CODE_ANCESTORS <= strict_affected_code:
        raise ValueError("known strict AI affected-code candidates were lost")
    weak_only_affected_code = {
        str(row["sha"])
        for row in candidate_rows
        if row["evidence_contracts"] == ["BROAD_METADATA_REGEX_CANDIDATE_ONLY"]
        and row["ancestor_of_affected_state"] is True
        and row["code_path_hits"]
    }
    if not KNOWN_WEAK_ONLY_AFFECTED_CODE_ANCESTORS <= weak_only_affected_code:
        raise ValueError("known weak AI affected-code candidates were lost")

    transitions = _exact_transitions(
        repository,
        source_v3_shas=source_v3_shas,
        frozen_ai_shas=frozen_ai_shas,
        weak_ai_shas=weak_ai_shas,
    )
    return {
        "schema_version": 1,
        "artifact_kind": "nltk_xml_path_traversal_recall_inventory",
        "repository_identity": REPOSITORY_IDENTITY,
        "advisory": ADVISORY,
        "inputs": {
            **dict(input_digests),
            "refs_digest": scan.get("refs_digest"),
            "matcher_contract": scan.get("matcher_contract"),
            "source_scan_predicate": scan.get("scan_predicate"),
            "affected_sha": AFFECTED_SHA,
            "fix_member_sha": FIX_MEMBER_SHA,
            "fix_merge_sha": FIX_MERGE_SHA,
            "code_paths": list(CODE_PATHS),
            "context_paths": list(CONTEXT_PATHS),
            "semantic_git_ere": GIT_SEMANTIC_ERE,
        },
        "finite_inventory": {
            "retained_union_commit_count": len(retained_shas),
            "retained_union_commit_sha256": _sha_inventory_digest(retained_shas),
            "retained_union_commit_shas": sorted(retained_shas),
            "frozen_commit_count": len(universe_shas),
            "current_all_ref_commit_count": len(all_ref_shas),
            "frozen_not_current_ref_count": len(universe_shas - all_ref_shas),
            "frozen_not_current_ref_shas": sorted(universe_shas - all_ref_shas),
            "current_ref_not_frozen_count": len(all_ref_shas - universe_shas),
            "current_ref_not_frozen_shas": sorted(all_ref_shas - universe_shas),
            "squash_candidate_count": len(closure_shas),
            "squash_member_count": len(member_shas),
            "squash_carrier_count": len(carrier_shas),
            "risk_path_history_count": len(path_shas),
            "semantic_history_count": len(semantic_shas),
            "source_v3_count": len(source_v3_shas),
            "frozen_observed_ai_count": len(frozen_ai_shas),
            "broad_metadata_candidate_count": len(weak_ai_shas),
            "ai_candidate_union_count": len(attribution_candidate_shas),
        },
        "priority_lanes": {
            "counts": dict(sorted(priority_counts.items())),
            "strict_ai_affected_code_ancestor_shas": sorted(strict_affected_code),
            "weak_only_affected_code_ancestor_shas": sorted(weak_only_affected_code),
            "semantic_and_any_ai_candidate_shas": sorted(
                semantic_shas & attribution_candidate_shas
            ),
            "affected_ancestor_and_any_ai_candidate_shas": sorted(
                {
                    str(row["sha"])
                    for row in candidate_rows
                    if row["ancestor_of_affected_state"] is True
                }
            ),
            "affected_code_and_any_ai_candidate_shas": sorted(
                {
                    str(row["sha"])
                    for row in candidate_rows
                    if row["ancestor_of_affected_state"] is True
                    and row["code_path_hits"]
                }
            ),
        },
        "ai_candidates": candidate_rows,
        "semantic_candidates": semantic_rows,
        "semantic_signal_counts": dict(sorted(semantic_counts.items())),
        "exact_local_transitions": transitions,
        "conservation": {
            "finite_union_commits_retained": len(retained_shas),
            "frozen_unreachable_commits_directly_scanned": len(direct_scan_shas),
            "broad_metadata_regex_scanned_commit_count": len(message_metadata),
            "ai_signal_is_rank_only": True,
            "semantic_signal_is_rank_only": True,
            "ancestry_is_rank_only": True,
            "weak_regex_never_upgraded_to_claim_grade": True,
            "squash_attribution_never_transferred_between_member_and_carrier": True,
            "model_negative_disposition": "DEFER_NOT_DELETE",
            "hard_filter_count": 0,
            "passed": True,
        },
        "claim_boundary": (
            "The finite Git inventory is lossless for the frozen/local-ref/squash "
            "union. AI-source recall is conditional on Source-v3, the frozen "
            "observation policy, and broad observable commit metadata; unmarked "
            "AI use remains unknowable. Weak regex hits are candidates, not "
            "publication-grade attribution."
        ),
    }


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    repository = args.repository.resolve()
    if not (repository / ".git").exists():
        raise SystemExit(f"repository is not a Git checkout: {repository}")

    raw_inputs = {
        "commit_universe": args.commit_universe.read_bytes(),
        "squash_candidates": args.squash_candidates.read_bytes(),
        "squash_relations": args.squash_relations.read_bytes(),
    }
    try:
        value = _build_inventory(
            repository,
            _load_jsonl(args.commit_universe),
            _load_jsonl(args.squash_candidates),
            _load_jsonl(args.squash_relations),
            input_digests={
                f"{name}_sha256": _sha256_bytes(raw) for name, raw in raw_inputs.items()
            },
        )
        _atomic_json(args.output, value)
    except (OSError, ValueError) as exc:
        raise SystemExit(str(exc)) from exc

    finite = value["finite_inventory"]
    lanes = value["priority_lanes"]
    print("NLTK XML-path causal inventory frozen")
    print(f"  retained union       : {finite['retained_union_commit_count']}")
    print(f"  current all refs     : {finite['current_all_ref_commit_count']}")
    print(f"  AI candidate union   : {finite['ai_candidate_union_count']}")
    print(
        "  affected AI code    : "
        f"{len(lanes['affected_code_and_any_ai_candidate_shas'])}"
    )
    print(f"  hard filters        : {value['conservation']['hard_filter_count']}")
    print(f"  output              : {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
