#!/usr/bin/env python3
from pathlib import Path
import json, subprocess, hashlib, os

ROOT = Path("/home/hanqing/agents/ai-slop")
OWNED = ROOT / "autoresearch/herdr-260814-w2-unknown9-grok46-high"
SLICE = ROOT / "autoresearch/orchestrator-260814-ghsa200-canvas/wave2/slice-01.jsonl"
CACHE = Path("/home/hanqing/.cache/ghsa200-worker-clones")
ADV_ROOTS = [
    Path("/home/hanqing/.cache/ghsa200-worker-clones/advisory-database"),
    ROOT / ".ai-slop/cache",
]
AI_PAT = ("Co-Authored-By: Claude", "Generated-By: Cursor", "Cursor Agent", "GPT-5", "Codex", "OpenAI Codex", "Claude ", "anthropic", "copilot", "Made-with: Cursor", "Generated by Claude", "Co-authored-by: Cursor")

rows = [json.loads(l) for l in SLICE.read_text().splitlines() if l.strip()]

def find_clone(repo):
    owner, name = repo.split("/", 1)
    key = f"{owner}__{name}"
    for camp in ["commit-oz", "commit-gn", "commit-af"]:
        for sub in ["repos", "clones"]:
            p = CACHE / camp / sub / key
            if p.exists():
                return str(p)
    # fallback walk shallow
    for p in CACHE.glob(f"*/*/{key}"):
        return str(p)
    return None

def git(repo, *args):
    try:
        r = subprocess.run(["git", "-C", repo, *args], capture_output=True, text=True, timeout=20)
        return r.returncode, (r.stdout or "")[:8000], (r.stderr or "")[:2000]
    except Exception as e:
        return 99, "", str(e)

def find_advisory(ghsa):
    ghsa_l = ghsa.lower()
    hits = []
    # github advisory db layout: advisories/github-reviewed/YYYY/MM/GHSA-...
    for root in [CACHE, ROOT]:
        for p in root.glob(f"**/{ghsa_l}.json"):
            hits.append(str(p))
            if len(hits) >= 3:
                return hits
        for p in root.glob(f"**/{ghsa}.json"):
            hits.append(str(p))
            if len(hits) >= 3:
                return hits
    return hits

out = []
for i, r in enumerate(rows):
    b = r.get("best") or {}
    repo = r.get("repository")
    clone = find_clone(repo)
    ai = b.get("ai_sha")
    fix = b.get("fix")
    parent = b.get("parent")
    rec = {
        "idx": i,
        "ghsa_id": r.get("ghsa_id"),
        "repository": repo,
        "summary": r.get("summary"),
        "ai_sha": ai,
        "fix": fix,
        "parent": parent,
        "n_parents": b.get("n_parents"),
        "atomic_first_parent": b.get("atomic_first_parent"),
        "blame_files": b.get("blame_files"),
        "history_files": b.get("history_files"),
        "commit_refs": r.get("commit_refs"),
        "clone": clone,
        "ai_exists": None,
        "fix_exists": None,
        "parent_exists": None,
        "ai_subject": None,
        "ai_body": None,
        "ai_author": None,
        "ai_marker": None,
        "ai_np": None,
        "fix_subject": None,
        "fix_marker": None,
        "adv_hits": [],
    }
    if clone and ai:
        code, outp, err = git(clone, "cat-file", "-t", ai)
        rec["ai_exists"] = outp.strip() if code == 0 else f"missing:{err.strip()[:200]}"
        code, outp, err = git(clone, "log", "-1", "--format=%P%n%an <%ae>%n%s%n%b", ai)
        if code == 0:
            lines = outp.splitlines()
            rec["ai_np"] = (lines[0].count(" ") + 1) if lines and lines[0] else 0
            rec["ai_author"] = lines[1] if len(lines) > 1 else None
            rec["ai_subject"] = lines[2] if len(lines) > 2 else None
            rec["ai_body"] = "\n".join(lines[3:40])
            blob = outp.lower()
            rec["ai_marker"] = [p for p in AI_PAT if p.lower() in blob]
        if parent:
            code, outp, err = git(clone, "cat-file", "-t", parent)
            rec["parent_exists"] = outp.strip() if code == 0 else f"missing"
        if fix:
            code, outp, err = git(clone, "cat-file", "-t", fix)
            rec["fix_exists"] = outp.strip() if code == 0 else f"missing:{err.strip()[:120]}"
            code, outp, err = git(clone, "log", "-1", "--format=%s%n%b", fix)
            if code == 0:
                rec["fix_subject"] = outp.splitlines()[0] if outp else None
                blob = outp.lower()
                rec["fix_marker"] = [p for p in AI_PAT if p.lower() in blob]
    rec["adv_hits"] = find_advisory(r.get("ghsa_id") or "")
    out.append(rec)

(OWNED / "_evidence.json").write_text(json.dumps(out, indent=2)[:200000])
print("WROTE", len(out), "clone_ok", sum(1 for x in out if x["clone"]), "ai_ok", sum(1 for x in out if x["ai_exists"]=="commit"))
